<?php

return [
    'sections' => [
        'hero' => [
            'eyebrow' => 'LADYSTARS · HAIR SYSTEM & TOUPEE',
            'title' => 'Vẻ đẹp tự nhiên, được thiết kế riêng cho bạn.',
            'description' => 'Khám phá giải pháp tóc được lựa chọn theo chất liệu, kiểu đế, màu sắc và nhu cầu sử dụng của riêng bạn.',
            'primary_label' => 'Khám phá sản phẩm',
            'primary_url' => '/san-pham',
            'image_position_x' => 50,
            'image_position_y' => 50,
            'secondary_label' => 'Nhận tư vấn',
            'secondary_url' => '/lien-he',
            'trust_items' => ['Chất liệu được tuyển chọn', 'Tư vấn theo nhu cầu', 'Chính sách rõ ràng'],
            'note_label' => 'Lựa chọn theo bạn',
            'note_value' => 'Màu · kiểu · mật độ',
        ],
        'consultation' => [
            'kicker' => 'TƯ VẤN CÙNG LADYSTARS',
            'title' => 'Chưa biết nên bắt đầu từ đâu?',
            'description' => 'Chọn điều bạn đang quan tâm, LADYSTARS sẽ hướng dẫn bước tiếp theo phù hợp.',
            'options' => ['Che tóc thưa', 'Che vùng đỉnh', 'Thay đổi kiểu tóc'],
            'cta_label' => 'Bắt đầu tư vấn',
            'cta_url' => '/dich-vu-cham-soc',
        ],
        'products' => [
            'kicker' => 'KHÁM PHÁ THEO NHU CẦU',
            'title' => 'Danh mục sản phẩm và dịch vụ',
            'description' => 'Tìm lựa chọn phù hợp với phong cách, nhu cầu sử dụng và cảm giác tự nhiên bạn mong muốn.',
            'featured_label' => 'Nổi bật',
            'view_all_label' => 'Xem tất cả sản phẩm',
            'view_all_url' => '/san-pham',
        ],
        'brand_story' => [
            'kicker' => 'CÂU CHUYỆN LADYSTARS',
            'title' => 'Không chỉ là mái tóc, đó là cách bạn cảm nhận về chính mình.',
            'description' => 'LADYSTARS hướng đến trải nghiệm lựa chọn tóc rõ ràng, nhẹ nhàng và tôn trọng dấu ấn riêng của mỗi người.',
            'image_alt' => 'Minh họa phong cách mềm mại của LADYSTARS',
            'values' => [
                ['title' => 'Cá nhân hóa', 'description' => 'Mỗi gợi ý bắt đầu từ nhu cầu, kiểu tóc và nhịp sống riêng của bạn.'],
                ['title' => 'Tự nhiên', 'description' => 'Ưu tiên vẻ ngoài hài hòa, tinh tế và dễ kết hợp cùng phong cách thường ngày.'],
                ['title' => 'Thoải mái', 'description' => 'Tập trung vào trải nghiệm sử dụng lâu dài, nhẹ nhàng và tự tin hơn.'],
                ['title' => 'Minh bạch', 'description' => 'Chất liệu, lựa chọn và chính sách được trình bày rõ ràng để bạn dễ quyết định.'],
            ],
            'cta_label' => 'Khám phá LADYSTARS',
            'cta_url' => '/gioi-thieu',
        ],
        'solutions' => [
            'kicker' => 'LỰA CHỌN DÀNH CHO BẠN',
            'title' => 'Giải pháp tinh tế cho từng mong muốn riêng.',
            'description' => 'Từ cảm giác tự nhiên hằng ngày đến một diện mạo mới mẻ, LADYSTARS giúp bạn hiểu rõ lựa chọn trước khi quyết định.',
            'bullets' => ['Gợi ý theo nhu cầu và phong cách', 'Dễ dàng hình dung chất liệu và kiểu tóc', 'Hướng dẫn sử dụng, chăm sóc rõ ràng'],
            'cta_label' => 'Xem hướng dẫn lựa chọn',
            'cta_url' => '/dich-vu-cham-soc',
            'art_text' => "Soft style,\nstrong confidence.",
            'image_path' => null,
            'image_alt' => 'Ảnh minh họa giải pháp dành cho bạn',
        ],
        'styles' => [
            'kicker' => 'STYLE INSPIRATION',
            'title' => 'Tìm cảm hứng cho phong cách của bạn',
            'items' => [
                ['title' => 'Tự nhiên hằng ngày', 'description' => 'Nhẹ nhàng, hài hòa và dễ chăm sóc cho nhịp sống năng động.', 'url' => '/san-pham', 'image_path' => null, 'image_alt' => 'Phong cách tự nhiên hằng ngày'],
                ['title' => 'Thanh lịch công sở', 'description' => 'Gọn gàng, chỉn chu với đường nét mềm mại và hiện đại.', 'url' => '/san-pham', 'image_path' => null, 'image_alt' => 'Phong cách thanh lịch công sở'],
                ['title' => 'Nổi bật sự kiện', 'description' => 'Tạo điểm nhấn tinh tế khi bạn muốn thay đổi phong cách.', 'url' => '/san-pham', 'image_path' => null, 'image_alt' => 'Phong cách nổi bật cho sự kiện'],
            ],
        ],
        'process' => [
            'kicker' => 'QUY TRÌNH LADYSTARS',
            'title' => 'Đồng hành cùng bạn, từng bước nhẹ nhàng',
            'description' => 'Bốn bước đơn giản để bạn bắt đầu với cảm giác chủ động và tự tin hơn.',
            'steps' => [
                ['number' => '01', 'title' => 'Lắng nghe nhu cầu', 'description' => 'Chia sẻ mong muốn, thói quen và cảm giác bạn đang tìm kiếm.', 'image_path' => null, 'image_alt' => 'Bước lắng nghe nhu cầu'],
                ['number' => '02', 'title' => 'Tư vấn lựa chọn', 'description' => 'Cùng xem kiểu dáng, chất liệu và lựa chọn phù hợp.', 'image_path' => null, 'image_alt' => 'Bước tư vấn lựa chọn'],
                ['number' => '03', 'title' => 'Hoàn thiện phong cách', 'description' => 'Điều chỉnh để tổng thể hài hòa với diện mạo của bạn.', 'image_path' => null, 'image_alt' => 'Bước hoàn thiện phong cách'],
                ['number' => '04', 'title' => 'Đồng hành chăm sóc', 'description' => 'Nhận hướng dẫn sử dụng và chăm sóc rõ ràng sau lựa chọn.', 'image_path' => null, 'image_alt' => 'Bước đồng hành chăm sóc'],
            ],
            'cta_label' => 'Đặt lịch tư vấn',
            'cta_url' => '/lien-he',
        ],
        'testimonials' => [
            'kicker' => 'CẢM NHẬN TỪ KHÁCH HÀNG',
            'title' => 'Những câu chuyện đầy tự tin',
            'items' => [
                ['quote' => 'Mọi lựa chọn đều được giải thích rất dễ hiểu, nên tôi thấy an tâm hơn khi quyết định.', 'customer' => 'Khách hàng LADYSTARS', 'label' => 'Tư vấn lựa chọn', 'detail_title' => 'Một lựa chọn rõ ràng và an tâm hơn', 'detail' => 'Từ những băn khoăn ban đầu, khách hàng được giải thích từng lựa chọn về kiểu dáng, chất liệu và cách sử dụng. Quá trình tư vấn rõ ràng giúp quyết định trở nên nhẹ nhàng, chủ động và phù hợp hơn với nhu cầu thực tế.', 'image_path' => null, 'image_alt' => 'Khách hàng chia sẻ trải nghiệm tư vấn lựa chọn'],
                ['quote' => 'Không khí nhẹ nhàng và tinh tế. Tôi thích cách đội ngũ lắng nghe phong cách riêng của mình.', 'customer' => 'Khách hàng LADYSTARS', 'label' => 'Trải nghiệm tư vấn', 'detail_title' => 'Được lắng nghe theo phong cách riêng', 'detail' => 'Buổi tư vấn bắt đầu từ thói quen, mong muốn và cảm giác mà khách hàng đang tìm kiếm. Không gian nhẹ nhàng cùng cách trao đổi tôn trọng dấu ấn cá nhân tạo nên một trải nghiệm gần gũi và đáng nhớ.', 'image_path' => null, 'image_alt' => 'Khách hàng chia sẻ trải nghiệm được lắng nghe'],
                ['quote' => 'Tôi muốn một diện mạo tự nhiên và kết quả khiến tôi cảm thấy tự tin trong mọi ngày.', 'customer' => 'Khách hàng LADYSTARS', 'label' => 'Phong cách hằng ngày', 'detail_title' => 'Tự nhiên hơn trong từng ngày', 'detail' => 'Lựa chọn cuối cùng hướng đến sự hài hòa, dễ sử dụng và phù hợp với nhịp sống thường ngày. Kết quả không chỉ thay đổi diện mạo mà còn mang lại cảm giác tự tin và thoải mái hơn.', 'image_path' => null, 'image_alt' => 'Khách hàng với phong cách tự nhiên hằng ngày'],
            ],
        ],
        'contact' => [
            'kicker' => 'KẾT NỐI LADYSTARS',
            'title' => 'Chọn cách bắt đầu phù hợp với bạn.',
            'description' => 'Đội ngũ LADYSTARS sẵn sàng lắng nghe nhu cầu và giúp bạn tìm đúng bước tiếp theo.',
            'cards' => [
                ['title' => 'Đặt lịch tư vấn', 'description' => 'Chọn thời điểm thuận tiện để bắt đầu cuộc trò chuyện.', 'url' => '/lien-he'],
                ['title' => 'Nhận hướng dẫn', 'description' => 'Tìm hiểu các tiêu chí quan trọng trước khi lựa chọn.', 'url' => '/dich-vu-cham-soc'],
            ],
        ],
        'insights' => [
            'kicker' => 'CẨM NANG LADYSTARS',
            'title' => 'Thông tin hữu ích trước khi lựa chọn',
            'items' => [
                ['title' => 'Dịch vụ chăm sóc tóc', 'description' => 'Bắt đầu từ nhu cầu sử dụng, vùng tóc cần quan tâm và cảm giác tự nhiên bạn mong muốn.', 'url' => '/dich-vu-cham-soc'],
                ['title' => 'Chính sách giao hàng', 'description' => 'Tìm hiểu cách LADYSTARS chuẩn bị và đồng hành cùng đơn hàng của bạn.', 'url' => '/chinh-sach-giao-hang'],
                ['title' => 'Chính sách đổi trả', 'description' => 'Những thông tin cần biết để bạn luôn chủ động trong quá trình mua sắm.', 'url' => '/chinh-sach-doi-tra'],
            ],
        ],
        'final_cta' => [
            'kicker' => 'BẮT ĐẦU CÙNG LADYSTARS',
            'title' => 'Bạn đã sẵn sàng tìm kiểu tóc dành riêng cho mình?',
            'description' => 'Khám phá sản phẩm hoặc nhận hướng dẫn từ đội ngũ LADYSTARS theo nhịp của riêng bạn.',
            'primary_label' => 'Đặt lịch tư vấn',
            'primary_url' => '/lien-he',
            'secondary_label' => 'Khám phá sản phẩm',
            'secondary_url' => '/san-pham',
        ],
        'floating_contact' => [
            'trigger_label' => 'Hỗ trợ',
            'consultation_label' => 'Đặt lịch tư vấn',
            'consultation_url' => '/lien-he',
            'guide_label' => 'Xem hướng dẫn lựa chọn',
            'guide_url' => '/dich-vu-cham-soc',
        ],
    ],
];
