<?php

use App\Http\Controllers\Api\V1\Account\AccountController;
use App\Http\Controllers\Api\V1\Account\CartController;
use App\Http\Controllers\Api\V1\Account\CheckoutController;
use App\Http\Controllers\Api\V1\Account\OrderController;
use App\Http\Controllers\Api\V1\Admin\BrandManagementController;
use App\Http\Controllers\Api\V1\Admin\CatalogManagementController;
use App\Http\Controllers\Api\V1\Admin\CatalogContentManagementController;
use App\Http\Controllers\Api\V1\Admin\ContactPageManagementController;
use App\Http\Controllers\Api\V1\Admin\ConsultationManagementController;
use App\Http\Controllers\Api\V1\Admin\AboutManagementController;
use App\Http\Controllers\Api\V1\Admin\DashboardController;
use App\Http\Controllers\Api\V1\Admin\NewsManagementController;
use App\Http\Controllers\Api\V1\Admin\OperationsController;
use App\Http\Controllers\Api\V1\Admin\ProductManagementController;
use App\Http\Controllers\Api\V1\Admin\ServiceManagementController;
use App\Http\Controllers\Api\V1\Auth\AuthController;
use App\Http\Controllers\Api\V1\Store\AboutController;
use App\Http\Controllers\Api\V1\Store\CatalogController;
use App\Http\Controllers\Api\V1\Store\CatalogContentController;
use App\Http\Controllers\Api\V1\Store\ConsultationRequestController;
use App\Http\Controllers\Api\V1\Store\ContactPageController;
use App\Http\Controllers\Api\V1\Store\NewsController;
use App\Http\Controllers\Api\V1\Store\NewsPageController;
use App\Http\Controllers\Api\V1\Store\GuideController;
use App\Http\Controllers\Api\V1\Store\GuidePageController;
use App\Http\Controllers\Api\V1\Store\GuestCheckoutController;
use App\Http\Controllers\Api\V1\Store\HomePageController;
use App\Http\Controllers\Api\V1\Admin\NewsPageContentManagementController;
use App\Http\Controllers\Api\V1\Admin\GuidePageContentManagementController;
use App\Http\Controllers\Api\V1\Admin\HomePageManagementController;
use App\Http\Controllers\Api\V1\Store\PromotionPageController;
use App\Http\Controllers\Api\V1\Admin\PromotionPageContentManagementController;
use App\Http\Controllers\Api\V1\Admin\StorePageManagementController;
use App\Http\Controllers\Api\V1\Store\ProductController;
use App\Http\Controllers\Api\V1\Store\StorePageController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::prefix('auth')->group(function () {
        Route::post('register', [AuthController::class, 'register']);
        Route::post('login', [AuthController::class, 'login']);
        Route::post('forgot-password', [AuthController::class, 'forgotPassword']);
        Route::post('reset-password', [AuthController::class, 'resetPassword']);
        Route::middleware('auth:sanctum')->group(function () {
            Route::get('me', [AuthController::class, 'me']);
            Route::post('logout', [AuthController::class, 'logout']);
        });
    });

    Route::get('categories', [CatalogController::class, 'categories']);
    Route::get('categories/{slug}', [CatalogController::class, 'category']);
    Route::get('brands', [CatalogController::class, 'brands']);
    Route::get('attributes', [CatalogController::class, 'attributes']);
    Route::get('catalog/content', [CatalogContentController::class, 'products']);
    Route::get('catalog/content/category/{slug}', [CatalogContentController::class, 'category']);
    Route::get('hair-guide', [CatalogContentController::class, 'hairGuide']);
    Route::get('catalog/filters', [CatalogController::class, 'filters']);
    Route::post('consultation-requests', [ConsultationRequestController::class, 'store'])->middleware('throttle:10,1');
    Route::get('products/featured', [ProductController::class, 'featured']);
    Route::get('products/new', [ProductController::class, 'newest']);
    Route::get('products/sale', [ProductController::class, 'sale']);
    Route::get('products', [ProductController::class, 'index']);
    Route::get('products/{slug}', [ProductController::class, 'show']);
    Route::post('guest-checkout/preview', [GuestCheckoutController::class, 'preview'])->middleware('throttle:20,1');
    Route::post('guest-checkout/place-order', [GuestCheckoutController::class, 'place'])->middleware('throttle:10,1');

    Route::get('about', [AboutController::class, 'index']);
    Route::get('seo/{pageKey}', [AboutController::class, 'seo']);
    Route::get('news', [NewsController::class, 'index']);
    Route::get('news/{slug}', [NewsController::class, 'show']);
    Route::get('news-page', [NewsPageController::class, 'index']);
    Route::get('guides-page', [GuidePageController::class, 'index']);
    Route::get('guides/{slug}', [GuideController::class, 'show']);
    Route::get('promotions-page', [PromotionPageController::class, 'index']);
    Route::get('promotions/{slug}', [PromotionPageController::class, 'show']);
    Route::get('home-page', [HomePageController::class, 'show']);
    Route::get('store-page', [StorePageController::class, 'index']);
    Route::get('contact-page', [ContactPageController::class, 'index']);

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('account/profile', [AccountController::class, 'profile']);
        Route::put('account/profile', [AccountController::class, 'updateProfile']);
        Route::put('account/password', [AccountController::class, 'updatePassword']);
        Route::get('account/addresses', [AccountController::class, 'addresses']);
        Route::post('account/addresses', [AccountController::class, 'storeAddress']);
        Route::put('account/addresses/{id}', [AccountController::class, 'updateAddress']);
        Route::delete('account/addresses/{id}', [AccountController::class, 'deleteAddress']);
        Route::patch('account/addresses/{id}/default', [AccountController::class, 'defaultAddress']);
        Route::get('cart', [CartController::class, 'index']);
        Route::post('cart/items', [CartController::class, 'store']);
        Route::patch('cart/items/{id}', [CartController::class, 'update']);
        Route::delete('cart/items/{id}', [CartController::class, 'destroy']);
        Route::delete('cart', [CartController::class, 'clear']);
        Route::post('checkout/preview', [CheckoutController::class, 'preview']);
        Route::post('checkout/place-order', [CheckoutController::class, 'place']);
        Route::get('account/orders', [OrderController::class, 'index']);
        Route::get('account/orders/{orderNumber}', [OrderController::class, 'show']);
        Route::post('account/orders/{orderNumber}/cancel', [OrderController::class, 'cancel']);
        Route::get('account/wishlist', [AccountController::class, 'wishlist']);
        Route::post('account/wishlist/{product}', [AccountController::class, 'addWishlist']);
        Route::delete('account/wishlist/{product}', [AccountController::class, 'removeWishlist']);
        Route::post('account/reviews', [AccountController::class, 'storeReview']);
        Route::put('account/reviews/{id}', [AccountController::class, 'updateReview']);
        Route::delete('account/reviews/{id}', [AccountController::class, 'deleteReview']);
    });

    Route::prefix('admin')->group(function () {
        Route::post('auth/login', [AuthController::class, 'adminLogin']);
        Route::middleware(['auth:sanctum', 'admin'])->group(function () {
            Route::post('auth/logout', [AuthController::class, 'logout']);
            Route::get('auth/me', [AuthController::class, 'me']);
            Route::get('dashboard/summary', [DashboardController::class, 'summary']);
            Route::get('dashboard/revenue', [DashboardController::class, 'revenue']);
            Route::get('dashboard/order-statuses', [DashboardController::class, 'orderStatuses']);
            Route::get('dashboard/top-products', [DashboardController::class, 'topProducts']);
            Route::get('dashboard/low-stock', [DashboardController::class, 'lowStock']);

            Route::get('categories', [CatalogManagementController::class, 'categories']);
            Route::get('brands', [BrandManagementController::class, 'index']);
            Route::post('brands', [BrandManagementController::class, 'store']);
            Route::put('brands/{brand}', [BrandManagementController::class, 'update']);
            Route::delete('brands/{brand}', [BrandManagementController::class, 'destroy']);
            Route::get('catalog/content', [CatalogContentManagementController::class, 'index']);
            Route::get('catalog/content/{pageKey}', [CatalogContentManagementController::class, 'show']);
            Route::put('catalog/content/{pageKey}', [CatalogContentManagementController::class, 'update']);
            Route::post('catalog/content/{pageKey}/images', [CatalogContentManagementController::class, 'uploadImage']);
            Route::delete('catalog/content/{pageKey}/images', [CatalogContentManagementController::class, 'deleteImage']);
            Route::get('consultation-requests', [ConsultationManagementController::class, 'index']);
            Route::patch('consultation-requests/{consultationRequest}/status', [ConsultationManagementController::class, 'updateStatus']);
            Route::get('services', [ServiceManagementController::class, 'index']);
            Route::post('services', [ServiceManagementController::class, 'store']);
            Route::get('services/{service}', [ServiceManagementController::class, 'show']);
            Route::put('services/{service}', [ServiceManagementController::class, 'update']);
            Route::patch('services/{service}/status', [ServiceManagementController::class, 'status']);
            Route::post('services/{service}/image', [ServiceManagementController::class, 'uploadImage']);
            Route::delete('services/{service}/image', [ServiceManagementController::class, 'deleteImage']);
            Route::delete('services/{service}', [ServiceManagementController::class, 'destroy']);
            Route::post('categories', [CatalogManagementController::class, 'storeCategory']);
            Route::patch('categories/reorder', [CatalogManagementController::class, 'reorderCategories']);
            Route::get('categories/{category}', [CatalogManagementController::class, 'showCategory']);
            Route::put('categories/{category}', [CatalogManagementController::class, 'updateCategory']);
            Route::delete('categories/{category}', [CatalogManagementController::class, 'deleteCategory']);
            Route::patch('categories/{category}/status', [CatalogManagementController::class, 'categoryStatus']);

            Route::get('products', [ProductManagementController::class, 'index']);
            Route::post('products', [ProductManagementController::class, 'store']);
            Route::get('products/{product}', [ProductManagementController::class, 'show']);
            Route::put('products/{product}', [ProductManagementController::class, 'update']);
            Route::delete('products/{product}', [ProductManagementController::class, 'destroy']);
            Route::patch('products/{product}/status', [ProductManagementController::class, 'status']);
            Route::post('products/{product}/images', [ProductManagementController::class, 'uploadImages']);
            Route::post('products/{product}/video', [ProductManagementController::class, 'uploadVideo']);
            Route::delete('products/{product}/video', [ProductManagementController::class, 'deleteVideo']);
            Route::patch('products/{product}/images/reorder', [ProductManagementController::class, 'reorderImages']);
            Route::delete('products/{product}/images/{image}', [ProductManagementController::class, 'deleteImage']);
            Route::patch('products/{product}/images/{image}', [ProductManagementController::class, 'updateImage']);
            Route::patch('products/{product}/images/{image}/primary', [ProductManagementController::class, 'primaryImage']);
            Route::post('products/{product}/variants', [ProductManagementController::class, 'storeVariant']);
            Route::put('products/{product}/variants/{variant}', [ProductManagementController::class, 'updateVariant']);
            Route::delete('products/{product}/variants/{variant}', [ProductManagementController::class, 'deleteVariant']);

            Route::get('attributes', [CatalogManagementController::class, 'attributes']);
            Route::post('attributes', [CatalogManagementController::class, 'storeAttribute']);
            Route::put('attributes/{attribute}', [CatalogManagementController::class, 'updateAttribute']);
            Route::delete('attributes/{attribute}', [CatalogManagementController::class, 'deleteAttribute']);
            Route::post('attributes/{attribute}/values', [CatalogManagementController::class, 'storeAttributeValue']);
            Route::put('attributes/{attribute}/values/{value}', [CatalogManagementController::class, 'updateAttributeValue']);
            Route::delete('attributes/{attribute}/values/{value}', [CatalogManagementController::class, 'deleteAttributeValue']);
            Route::post('attributes/{attribute}/values/{value}/image', [CatalogManagementController::class, 'uploadAttributeValueImage']);
            Route::delete('attributes/{attribute}/values/{value}/image', [CatalogManagementController::class, 'deleteAttributeValueImage']);
            Route::get('branches', [CatalogManagementController::class, 'branches']);
            Route::post('branches', [CatalogManagementController::class, 'storeBranch']);
            Route::put('branches/{branch}', [CatalogManagementController::class, 'updateBranch']);
            Route::delete('branches/{branch}', [CatalogManagementController::class, 'deleteBranch']);

            Route::get('inventory', [OperationsController::class, 'inventory']);
            Route::get('inventory/transactions', [OperationsController::class, 'transactions']);
            Route::post('inventory/import', [OperationsController::class, 'adjustInventory']);
            Route::post('inventory/adjust', [OperationsController::class, 'adjustInventory']);
            Route::post('inventory/transfer', [OperationsController::class, 'transferInventory']);
            Route::get('inventory/low-stock', [OperationsController::class, 'lowStock']);
            Route::get('orders', [OperationsController::class, 'orders']);
            Route::get('orders/{order}', [OperationsController::class, 'showOrder']);
            Route::patch('orders/{order}/status', [OperationsController::class, 'orderStatus']);
            Route::patch('orders/{order}/payment-status', [OperationsController::class, 'paymentStatus']);
            Route::post('orders/{order}/cancel', [OperationsController::class, 'cancelOrder']);
            Route::post('orders/{order}/notes', [OperationsController::class, 'notes']);
            Route::get('customers', [OperationsController::class, 'customers']);
            Route::get('customers/{user}', [OperationsController::class, 'showCustomer']);
            Route::patch('customers/{user}/status', [OperationsController::class, 'customerStatus']);
            Route::get('reviews', [OperationsController::class, 'reviews']);
            Route::patch('reviews/{review}/status', [OperationsController::class, 'reviewStatus']);
            Route::delete('reviews/{review}', [OperationsController::class, 'deleteReview']);
            Route::get('coupons', [OperationsController::class, 'coupons']);
            Route::post('coupons', [OperationsController::class, 'storeCoupon']);
            Route::put('coupons/{coupon}', [OperationsController::class, 'updateCoupon']);
            Route::delete('coupons/{coupon}', [OperationsController::class, 'deleteCoupon']);
            Route::post('import/products', [OperationsController::class, 'importProducts']);
            Route::get('export/{resource}', [OperationsController::class, 'export']);
            Route::get('barcodes', [OperationsController::class, 'barcodes']);
            Route::post('barcodes/{variant}/generate', [OperationsController::class, 'generateBarcode']);
            Route::get('settings', [OperationsController::class, 'settings']);
            Route::put('settings', [OperationsController::class, 'updateSettings']);

            Route::get('home-page', [HomePageManagementController::class, 'show']);
            Route::put('home-page', [HomePageManagementController::class, 'update']);
            Route::post('home-page/hero-image', [HomePageManagementController::class, 'uploadHeroImage']);
            Route::delete('home-page/hero-image', [HomePageManagementController::class, 'deleteHeroImage']);
            Route::post('home-page/brand-story-image', [HomePageManagementController::class, 'uploadBrandStoryImage']);
            Route::delete('home-page/brand-story-image', [HomePageManagementController::class, 'deleteBrandStoryImage']);
            Route::post('home-page/section-images/{slot}/{index?}', [HomePageManagementController::class, 'uploadSectionImage']);
            Route::delete('home-page/section-images/{slot}/{index?}', [HomePageManagementController::class, 'deleteSectionImage']);

            Route::get('store-page', [StorePageManagementController::class, 'index']);
            Route::put('store-page', [StorePageManagementController::class, 'update']);
            Route::post('store-page/images/{slot}', [StorePageManagementController::class, 'uploadImage']);
            Route::delete('store-page/images/{slot}', [StorePageManagementController::class, 'deleteImage']);
            Route::post('store-page/items', [StorePageManagementController::class, 'storeItem']);
            Route::patch('store-page/items/reorder', [StorePageManagementController::class, 'reorderItems']);
            Route::put('store-page/items/{item}', [StorePageManagementController::class, 'updateItem']);
            Route::delete('store-page/items/{item}', [StorePageManagementController::class, 'deleteItem']);
            Route::patch('store-page/items/{item}/status', [StorePageManagementController::class, 'itemStatus']);
            Route::post('store-page/items/{item}/image', [StorePageManagementController::class, 'uploadItemImage']);
            Route::delete('store-page/items/{item}/image', [StorePageManagementController::class, 'deleteItemImage']);
            Route::post('store-page/branches/{branch}/image', [StorePageManagementController::class, 'uploadBranchImage']);
            Route::delete('store-page/branches/{branch}/image', [StorePageManagementController::class, 'deleteBranchImage']);

            Route::get('contact-page', [ContactPageManagementController::class, 'show']);
            Route::put('contact-page', [ContactPageManagementController::class, 'update']);
            Route::post('contact-page/images/{slot}', [ContactPageManagementController::class, 'uploadImage']);
            Route::delete('contact-page/images/{slot}', [ContactPageManagementController::class, 'deleteImage']);

            Route::get('about/sections', [AboutManagementController::class, 'index']);
            Route::post('about/sections', [AboutManagementController::class, 'store']);
            Route::patch('about/reorder', [AboutManagementController::class, 'reorder']);
            Route::get('about/sections/{section}', [AboutManagementController::class, 'show']);
            Route::put('about/sections/{section}', [AboutManagementController::class, 'update']);
            Route::patch('about/sections/{section}/status', [AboutManagementController::class, 'status']);
            Route::post('about/sections/{section}/image', [AboutManagementController::class, 'uploadImage']);
            Route::delete('about/sections/{section}/image', [AboutManagementController::class, 'deleteImage']);
            Route::get('about/seos', [AboutManagementController::class, 'seos']);
            Route::put('about/seos/{pageKey}', [AboutManagementController::class, 'updateSeo']);

            Route::get('news', [NewsManagementController::class, 'index']);
            Route::post('news', [NewsManagementController::class, 'store']);
            Route::get('news/{article}', [NewsManagementController::class, 'show']);
            Route::put('news/{article}', [NewsManagementController::class, 'update']);
            Route::delete('news/{article}', [NewsManagementController::class, 'destroy']);
            Route::patch('news/{article}/status', [NewsManagementController::class, 'status']);
            Route::post('news/{article}/cover-image', [NewsManagementController::class, 'uploadCover']);
            Route::delete('news/{article}/cover-image', [NewsManagementController::class, 'deleteCover']);

            Route::get('news-page', [NewsPageContentManagementController::class, 'show']);
            Route::put('news-page', [NewsPageContentManagementController::class, 'update']);
            Route::post('news-page/cta-image', [NewsPageContentManagementController::class, 'uploadCtaImage']);
            Route::delete('news-page/cta-image', [NewsPageContentManagementController::class, 'deleteCtaImage']);

            Route::get('promotions', [NewsManagementController::class, 'index']);
            Route::post('promotions', [NewsManagementController::class, 'store']);
            Route::get('promotions/product-options', [NewsManagementController::class, 'promotionProductOptions']);
            Route::get('promotions/{article}', [NewsManagementController::class, 'show']);
            Route::put('promotions/{article}', [NewsManagementController::class, 'update']);
            Route::delete('promotions/{article}', [NewsManagementController::class, 'destroy']);
            Route::patch('promotions/{article}/status', [NewsManagementController::class, 'status']);
            Route::post('promotions/{article}/cover-image', [NewsManagementController::class, 'uploadCover']);
            Route::delete('promotions/{article}/cover-image', [NewsManagementController::class, 'deleteCover']);
            Route::get('promotions-page', [PromotionPageContentManagementController::class, 'show']);
            Route::put('promotions-page', [PromotionPageContentManagementController::class, 'update']);
            Route::post('promotions-page/cta-image', [PromotionPageContentManagementController::class, 'uploadCtaImage']);
            Route::delete('promotions-page/cta-image', [PromotionPageContentManagementController::class, 'deleteCtaImage']);

            Route::get('guides', [NewsManagementController::class, 'index']);
            Route::post('guides', [NewsManagementController::class, 'store']);
            Route::get('guides/{article}', [NewsManagementController::class, 'show']);
            Route::put('guides/{article}', [NewsManagementController::class, 'update']);
            Route::delete('guides/{article}', [NewsManagementController::class, 'destroy']);
            Route::patch('guides/{article}/status', [NewsManagementController::class, 'status']);
            Route::post('guides/{article}/cover-image', [NewsManagementController::class, 'uploadCover']);
            Route::delete('guides/{article}/cover-image', [NewsManagementController::class, 'deleteCover']);
            Route::post('guides/{article}/content-image', [NewsManagementController::class, 'uploadContentImage']);
            Route::delete('guides/{article}/content-image', [NewsManagementController::class, 'deleteContentImage']);
            Route::post('guides/{article}/video', [NewsManagementController::class, 'uploadVideo']);
            Route::delete('guides/{article}/video', [NewsManagementController::class, 'deleteVideo']);
            Route::get('guides-page', [GuidePageContentManagementController::class, 'show']);
            Route::put('guides-page', [GuidePageContentManagementController::class, 'update']);
            Route::post('guides-page/hero-image', [GuidePageContentManagementController::class, 'uploadHeroImage']);
            Route::delete('guides-page/hero-image', [GuidePageContentManagementController::class, 'deleteHeroImage']);
            Route::post('guides-page/cta-image', [GuidePageContentManagementController::class, 'uploadCtaImage']);
            Route::delete('guides-page/cta-image', [GuidePageContentManagementController::class, 'deleteCtaImage']);
        });
    });
});
