import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { EmptyState } from '../../components/common/EmptyState'
import { LoadingState } from '../../components/common/LoadingState'
import type { ApiResponse, Pagination, ReturnRequest, WarrantyRequest } from '../../types'
import { formatPrice, statusLabel } from '../../utils/format'

export function ReturnsAdminPage() {
  const { id } = useParams()
  const client = useQueryClient()
  const [filters, setFilters] = useState<Record<string, string>>({})
  const query = useQuery({ queryKey: ['admin-returns', id, filters], queryFn: async () => id ? (await apiClient.get<ApiResponse<ReturnRequest>>(`/admin/returns/${id}`)).data.data : (await apiClient.get<ApiResponse<Pagination<ReturnRequest>>>('/admin/returns', { params: filters })).data.data })
  const refundSummary = useQuery({ queryKey: ['admin-return-refund-summary', id], enabled: Boolean(id && (query.data as ReturnRequest | undefined)?.request_type === 'return' && ['received', 'completed'].includes((query.data as ReturnRequest).status)), queryFn: async () => (await apiClient.get<ApiResponse<{ suggested: number; already_refunded: number; remaining_payment: number }>>(`/admin/returns/${id}/refund-summary`)).data.data })
  if (query.isLoading) return <LoadingState />

  const refresh = async () => { await client.invalidateQueries({ queryKey: ['admin-returns'] }); await client.invalidateQueries({ queryKey: ['admin-return-refund-summary', id] }) }
  const action = async (name: string, payload = {}) => { try { await apiClient.post(`/admin/returns/${id}/${name}`, payload); await refresh(); toast.success('Đã cập nhật yêu cầu.') } catch { toast.error('Thao tác không hợp lệ.') } }

  if (!id) {
    const page = query.data as Pagination<ReturnRequest>
    return <AdminList title='Đổi / Trả' filters={<ReturnFilters onSubmit={setFilters} />}>{page?.data.length ? page.data.map((item) => <tr key={item.id}><td><Link className='font-bold text-emerald-800' to={`/admin/returns/${item.id}`}>{item.code}</Link></td><td>{item.order?.order_number}</td><td>{item.customer?.customer_name}</td><td>{item.request_type === 'exchange' ? 'Đổi hàng' : 'Trả hàng'}</td><td>{statusLabel[item.status] ?? item.status}</td><td>{new Date(item.requested_at).toLocaleDateString('vi-VN')}</td></tr>) : <tr><td colSpan={6}><EmptyState title='Không có yêu cầu' description='Không tìm thấy yêu cầu đổi / trả phù hợp.' /></td></tr>}</AdminList>
  }

  const item = query.data as ReturnRequest
  const receive = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await action('receive', { items: item.items.map((line) => ({ id: line.id, condition_status: String(form.get(`condition_${line.id}`)), restockable: form.get(`restock_${line.id}`) === 'on' })) }) }
  const createRefund = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiClient.post(`/admin/returns/${id}/refund`, { amount: Number(form.get('amount')), method: form.get('method'), transaction_code: form.get('transaction_code') || null, reason: form.get('reason') || 'Hoàn tiền theo yêu cầu đổi / trả' }); await refresh(); event.currentTarget.reset(); toast.success('Đã tạo giao dịch hoàn tiền chờ xử lý.') } catch { toast.error('Số tiền vượt giới hạn hoặc dữ liệu chưa hợp lệ.') } }
  const saveShipment = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); try { await apiClient.put(`/admin/returns/${id}/shipment`, { purpose: item.request_type === 'exchange' ? 'exchange_outbound' : 'return_inbound', carrier: form.carrier || null, tracking_number: form.tracking_number || null, tracking_url: form.tracking_url || null }); await refresh(); toast.success('Đã lưu vận chuyển hậu mãi.') } catch { toast.error('Không thể lưu vận chuyển.') } }
  const shipmentStatus = async (shipmentId: number, status: 'shipped' | 'delivered') => { try { await apiClient.patch(`/admin/returns/${id}/shipments/${shipmentId}/status`, { status }); await refresh(); toast.success('Đã cập nhật vận chuyển.') } catch { toast.error('Trạng thái vận chuyển không hợp lệ.') } }

  return <AdminDetail back='/admin/returns' title={item.code} status={item.status}>
    <div className='grid gap-2 sm:grid-cols-2'><Info label='Đơn hàng' value={item.order?.order_number ?? '-'} /><Info label='Khách hàng' value={`${item.customer?.customer_name ?? '-'} · ${item.customer?.customer_phone ?? ''}`} /><Info label='Hình thức' value={item.request_type === 'exchange' ? 'Đổi hàng' : 'Trả hàng'} /><Info label='Chi nhánh nhận' value={item.receiving_branch?.name ?? 'Theo đơn hàng'} /></div>
    <div className='grid gap-3'>{item.items.map((line) => <div className='rounded-xl bg-slate-50 p-4' key={line.id}><strong>{line.order_item?.product_name}</strong><p className='muted mt-1'>SKU: {line.order_item?.sku} · Số lượng: {line.quantity}</p><p>Lý do: {line.reason_code}{line.reason_detail ? ` — ${line.reason_detail}` : ''}</p>{line.replacement_variant && <p>Thay bằng: {line.replacement_variant.sku}</p>}</div>)}</div>
    <MediaGrid media={item.media} />
    <div className='flex flex-wrap gap-2'>{item.status === 'requested' && <button className='btn-primary' onClick={() => void action('review')}>Bắt đầu xem xét</button>}{item.status === 'reviewing' && <><button className='btn-primary' onClick={() => void action('approve')}>Duyệt yêu cầu</button><button className='btn-secondary text-red-700' onClick={() => void action('reject', { rejection_reason: 'Không đủ điều kiện theo chính sách' })}>Từ chối</button></>}{item.status === 'approved' && <button className='btn-secondary' onClick={() => void action('mark-returning')}>Đánh dấu đang hoàn hàng</button>}</div>
    {['approved', 'returning'].includes(item.status) && <form className='rounded-xl border p-4' onSubmit={receive}><h2 className='font-black'>Tiếp nhận sản phẩm</h2><div className='mt-3 grid gap-3'>{item.items.map((line) => <div className='grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-2' key={line.id}><label><span className='label'>{line.order_item?.product_name}</span><select className='input' name={`condition_${line.id}`}><option value='unused'>Chưa sử dụng</option><option value='opened'>Đã mở</option><option value='used'>Đã sử dụng</option><option value='damaged'>Hư hỏng</option><option value='defective'>Lỗi sản phẩm</option></select></label><label className='flex items-center gap-2 font-bold'><input type='checkbox' name={`restock_${line.id}`} /> Có thể nhập lại kho</label></div>)}</div><button className='btn-primary mt-3'>Xác nhận đã nhận hàng</button></form>}
    {item.status === 'received' && item.request_type === 'return' && <button className='btn-secondary justify-self-start' onClick={() => void action('complete')}>Hoàn tất yêu cầu</button>}
    {['received', 'completed'].includes(item.status) && item.request_type === 'return' && <section className='rounded-xl border p-4'><h2 className='font-black'>Hoàn tiền</h2><div className='mt-3 grid gap-2 sm:grid-cols-3'><Info label='Đề xuất' value={formatPrice(refundSummary.data?.suggested ?? 0)} /><Info label='Đã hoàn' value={formatPrice(refundSummary.data?.already_refunded ?? 0)} /><Info label='Còn có thể hoàn' value={formatPrice(refundSummary.data?.remaining_payment ?? 0)} /></div><form className='mt-4 grid gap-3 sm:grid-cols-2' onSubmit={createRefund}><label><span className='label'>Số tiền</span><input className='input' name='amount' type='number' min='1' max={refundSummary.data?.remaining_payment} defaultValue={refundSummary.data?.suggested ?? ''} required /></label><label><span className='label'>Phương thức</span><select className='input' name='method'><option value='manual_bank_transfer'>Chuyển khoản thủ công</option><option value='cash'>Tiền mặt</option><option value='manual'>Thủ công khác</option></select></label><input className='input' name='transaction_code' placeholder='Mã giao dịch (nếu có)' /><input className='input' name='reason' placeholder='Lý do hoàn tiền' /><button className='btn-primary sm:col-span-2'>Tạo hoàn tiền</button></form>{item.refunds?.map((refund) => <div className='mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3' key={refund.id}><span><strong>{refund.code}</strong> · {formatPrice(refund.amount)} · {statusLabel[refund.status] ?? refund.status}</span>{refund.status === 'pending' && <button className='btn-primary' onClick={async () => { await apiClient.post(`/admin/refunds/${refund.id}/complete`); await refresh() }}>Hoàn tất giao dịch</button>}</div>)}</section>}
    {item.request_type === 'exchange' && ['received', 'completed'].includes(item.status) && <ShipmentPanel shipments={item.shipments} onSubmit={saveShipment} onStatus={shipmentStatus} />}
  </AdminDetail>
}

export function WarrantiesAdminPage() {
  const { id } = useParams()
  const client = useQueryClient()
  const [filters, setFilters] = useState<Record<string, string>>({})
  const query = useQuery({ queryKey: ['admin-warranties', id, filters], queryFn: async () => id ? (await apiClient.get<ApiResponse<WarrantyRequest>>(`/admin/warranties/${id}`)).data.data : (await apiClient.get<ApiResponse<Pagination<WarrantyRequest>>>('/admin/warranties', { params: filters })).data.data })
  if (query.isLoading) return <LoadingState />
  const refresh = async () => client.invalidateQueries({ queryKey: ['admin-warranties'] })
  const action = async (name: string, payload = {}) => { try { await apiClient.post(`/admin/warranties/${id}/${name}`, payload); await refresh(); toast.success('Đã cập nhật bảo hành.') } catch { toast.error('Thao tác bảo hành không hợp lệ.') } }

  if (!id) {
    const page = query.data as Pagination<WarrantyRequest>
    return <AdminList title='Bảo hành' filters={<WarrantyFilters onSubmit={setFilters} />}>{page?.data.length ? page.data.map((item) => <tr key={item.id}><td><Link className='font-bold text-emerald-800' to={`/admin/warranties/${item.id}`}>{item.code}</Link></td><td>{item.order?.order_number}</td><td>{item.customer?.customer_name ?? item.order_item?.product_name}</td><td>{item.order_item?.product_name}</td><td>{statusLabel[item.status] ?? item.status}</td><td>{new Date(item.requested_at).toLocaleDateString('vi-VN')}</td></tr>) : <tr><td colSpan={6}><EmptyState title='Không có yêu cầu' description='Không tìm thấy yêu cầu bảo hành phù hợp.' /></td></tr>}</AdminList>
  }

  const item = query.data as WarrantyRequest
  const approve = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await action('approve', { actual_resolution: form.get('actual_resolution'), replacement_variant_id: form.get('replacement_variant_id') ? Number(form.get('replacement_variant_id')) : null }) }
  const saveShipment = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); try { await apiClient.put(`/admin/warranties/${id}/shipment`, { purpose: form.purpose, carrier: form.carrier || null, tracking_number: form.tracking_number || null, tracking_url: form.tracking_url || null }); await refresh(); toast.success('Đã lưu vận chuyển bảo hành.') } catch { toast.error('Không thể lưu vận chuyển.') } }
  const shipmentStatus = async (shipmentId: number, status: 'shipped' | 'delivered') => { try { await apiClient.patch(`/admin/warranties/${id}/shipments/${shipmentId}/status`, { status }); await refresh(); toast.success('Đã cập nhật vận chuyển.') } catch { toast.error('Trạng thái vận chuyển không hợp lệ.') } }

  return <AdminDetail back='/admin/warranties' title={item.code} status={item.status}>
    <div className='grid gap-2 sm:grid-cols-2'><Info label='Đơn hàng' value={item.order?.order_number ?? '-'} /><Info label='Khách hàng' value={`${item.customer?.customer_name ?? '-'} · ${item.customer?.customer_phone ?? ''}`} /><Info label='Sản phẩm' value={`${item.order_item?.product_name ?? '-'} · ${item.order_item?.sku ?? ''}`} /><Info label='Bảo hành snapshot' value={`${item.order_item?.warranty_days_snapshot ?? 0} ngày`} /><Info label='Sự cố' value={`${item.issue_type}: ${item.description}`} /><Info label='Chi nhánh nhận' value={item.receiving_branch?.name ?? 'Theo đơn hàng'} /></div>
    <MediaGrid media={item.media} />
    <div className='flex flex-wrap gap-2'>{item.status === 'requested' && <button className='btn-primary' onClick={() => void action('review')}>Bắt đầu xem xét</button>}{item.status === 'reviewing' && <button className='btn-secondary text-red-700' onClick={() => void action('reject', { rejection_reason: 'Không đủ điều kiện bảo hành' })}>Từ chối</button>}{item.status === 'approved' && <button className='btn-primary' onClick={() => void action('receive')}>Đã nhận sản phẩm</button>}{item.status === 'received' && <button className='btn-primary' onClick={() => void action('processing')}>Bắt đầu xử lý</button>}{item.status === 'processing' && <button className='btn-primary' onClick={() => void action('ready')}>Sẵn sàng bàn giao</button>}{item.status === 'ready' && <button className='btn-primary' onClick={() => void action('complete')}>Hoàn tất</button>}</div>
    {item.status === 'reviewing' && <form className='rounded-xl border p-4' onSubmit={approve}><h2 className='font-black'>Duyệt phương án</h2><div className='mt-3 grid gap-3 sm:grid-cols-2'><select className='input' name='actual_resolution'><option value='repair'>Sửa chữa</option><option value='replacement'>Thay thế</option></select><input className='input' name='replacement_variant_id' type='number' min='1' placeholder='ID biến thể thay thế (nếu có)' /></div><button className='btn-primary mt-3'>Duyệt bảo hành</button></form>}
    {['approved', 'received', 'processing', 'ready'].includes(item.status) && <WarrantyShipmentPanel shipments={item.shipments} onSubmit={saveShipment} onStatus={shipmentStatus} />}
  </AdminDetail>
}

function ReturnFilters({ onSubmit }: { onSubmit: (filters: Record<string, string>) => void }) { return <form className='card mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-8' onSubmit={(event) => { event.preventDefault(); onSubmit(cleanForm(event.currentTarget)) }}><input className='input' name='code' placeholder='Mã yêu cầu' /><input className='input' name='order_number' placeholder='Mã đơn' /><input className='input' name='customer' placeholder='Khách hàng' /><input className='input' name='phone' placeholder='Điện thoại' /><select className='input' name='request_type'><option value=''>Tất cả loại</option><option value='return'>Trả hàng</option><option value='exchange'>Đổi hàng</option></select><select className='input' name='status'><option value=''>Tất cả trạng thái</option>{['requested', 'reviewing', 'approved', 'returning', 'received', 'completed', 'rejected', 'cancelled'].map((status) => <option key={status} value={status}>{statusLabel[status] ?? status}</option>)}</select><input className='input' type='date' name='from' /><button className='btn-primary'>Lọc</button></form> }
function WarrantyFilters({ onSubmit }: { onSubmit: (filters: Record<string, string>) => void }) { return <form className='card mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4' onSubmit={(event) => { event.preventDefault(); onSubmit(cleanForm(event.currentTarget)) }}><input className='input' name='code' placeholder='Mã yêu cầu' /><input className='input' name='customer' placeholder='Khách hàng' /><select className='input' name='status'><option value=''>Tất cả trạng thái</option>{['requested', 'reviewing', 'approved', 'received', 'processing', 'ready', 'completed', 'rejected', 'cancelled'].map((status) => <option key={status} value={status}>{statusLabel[status] ?? status}</option>)}</select><button className='btn-primary'>Lọc</button></form> }
function cleanForm(form: HTMLFormElement) { return Object.fromEntries([...new FormData(form).entries()].filter(([, value]) => value !== '')) as Record<string, string> }
function AdminList({ title, filters, children }: { title: string; filters: React.ReactNode; children: React.ReactNode }) { return <div><h1 className='mb-6 text-3xl font-black'>{title}</h1>{filters}<div className='table-wrap'><table className='table'><thead><tr><th>Mã</th><th>Đơn hàng</th><th>Khách hàng</th><th>Loại / Sản phẩm</th><th>Trạng thái</th><th>Ngày</th></tr></thead><tbody>{children}</tbody></table></div></div> }
function AdminDetail({ back, title, status, children }: { back: string; title: string; status: string; children: React.ReactNode }) { return <div className='card p-6'><Link className='text-sm font-bold text-emerald-800' to={back}>← Quay lại danh sách</Link><div className='mt-4 flex justify-between gap-3'><h1 className='text-2xl font-black'>{title}</h1><span className='badge'>{statusLabel[status] ?? status}</span></div><div className='mt-5 grid gap-4'>{children}</div></div> }
function Info({ label, value }: { label: string; value: string }) { return <p><strong>{label}:</strong> {value}</p> }
function MediaGrid({ media }: { media?: Array<{ id: number; url: string }> }) { return media?.length ? <div><h2 className='font-black'>Ảnh minh chứng</h2><div className='mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5'>{media.map((image) => <a href={image.url} target='_blank' rel='noreferrer' key={image.id}><img className='aspect-square w-full rounded-xl border object-cover' src={image.url} alt='Ảnh minh chứng hậu mãi' /></a>)}</div></div> : null }
function ShipmentPanel({ shipments, onSubmit, onStatus }: { shipments: ReturnRequest['shipments']; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onStatus: (id: number, status: 'shipped' | 'delivered') => void }) { return <section className='rounded-xl border p-4'><h2 className='font-black'>Vận chuyển hàng đổi</h2><form className='mt-3 grid gap-3 sm:grid-cols-3' onSubmit={onSubmit}><input className='input' name='carrier' placeholder='Đơn vị vận chuyển' /><input className='input' name='tracking_number' placeholder='Mã vận đơn' /><input className='input' name='tracking_url' type='url' placeholder='Tracking URL' /><button className='btn-primary sm:col-span-3'>Lưu vận chuyển</button></form>{shipments?.map((shipment) => <div className='mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3' key={shipment.id}><span>{shipment.carrier || '-'} · {shipment.tracking_number || '-'} · {statusLabel[shipment.status] ?? shipment.status}</span><div className='flex gap-2'>{shipment.status === 'pending' && <button className='btn-primary' onClick={() => onStatus(shipment.id, 'shipped')}>Đã gửi</button>}{shipment.status === 'shipped' && <button className='btn-primary' onClick={() => onStatus(shipment.id, 'delivered')}>Đã giao</button>}</div></div>)}</section> }
function WarrantyShipmentPanel({ shipments, onSubmit, onStatus }: { shipments: WarrantyRequest['shipments']; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onStatus: (id: number, status: 'shipped' | 'delivered') => void }) { return <section className='rounded-xl border p-4'><h2 className='font-black'>Vận chuyển bảo hành</h2><form className='mt-3 grid gap-3 sm:grid-cols-2' onSubmit={onSubmit}><select className='input' name='purpose'><option value='warranty_inbound'>Khách gửi đến</option><option value='warranty_outbound'>Cửa hàng gửi trả</option></select><input className='input' name='carrier' placeholder='Đơn vị vận chuyển' /><input className='input' name='tracking_number' placeholder='Mã vận đơn' /><input className='input' name='tracking_url' type='url' placeholder='Tracking URL' /><button className='btn-primary sm:col-span-2'>Lưu vận chuyển</button></form>{shipments?.map((shipment) => <div className='mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3' key={shipment.id}><span>{shipment.purpose} · {shipment.tracking_number || '-'} · {statusLabel[shipment.status] ?? shipment.status}</span><div className='flex gap-2'>{shipment.status === 'pending' && <button className='btn-primary' onClick={() => onStatus(shipment.id, 'shipped')}>Đã gửi</button>}{shipment.status === 'shipped' && <button className='btn-primary' onClick={() => onStatus(shipment.id, 'delivered')}>Đã giao</button>}</div></div>)}</section> }
