import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { CalendarPlus } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { EmptyState } from '../../components/common/EmptyState'
import { LoadingState } from '../../components/common/LoadingState'
import type { ApiResponse, Appointment, AppointmentOptions, Pagination } from '../../types'
import { statusLabel } from '../../utils/format'
import { useAuth } from '../../stores/AuthContext'
import { can } from '../../features/auth/permissions'
import { downloadAppointmentIcs } from '../../utils/browserActions'

type Tab = 'list' | 'schedule' | 'blocks'
type Schedule = { id: number; branch_id: number; day_of_week: number; start_time: string; end_time: string; slot_minutes: number; capacity: number; is_active?: boolean }
type Block = { id: number; branch_id: number; start_at: string; end_at: string; reason?: string | null }
const weekdays = ['Chủ nhật', 'Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7']

export function AppointmentsAdminPage() {
  const { user } = useAuth(); const canManage = can(user, 'appointments.manage'); const canManageSchedule = can(user, 'appointments.schedule.manage')
  const client = useQueryClient()
  const [tab, setTab] = useState<Tab>('list')
  const [searchParams, setSearchParams] = useSearchParams()
  const filters = Object.fromEntries(searchParams.entries())
  const [rescheduleId, setRescheduleId] = useState<number | null>(null)
  const [rescheduleAt, setRescheduleAt] = useState('')
  const appointments = useQuery({ queryKey: ['admin-appointments', filters], queryFn: async () => (await apiClient.get<ApiResponse<Pagination<Appointment>>>('/admin/appointments', { params: filters })).data.data })
  const options = useQuery({ queryKey: ['appointment-options'], queryFn: async () => (await apiClient.get<ApiResponse<AppointmentOptions>>('/appointment-options')).data.data })
  const schedules = useQuery({ queryKey: ['admin-appointment-schedules'], queryFn: async () => (await apiClient.get<ApiResponse<Schedule[]>>('/admin/appointment-schedules')).data.data })
  const blocks = useQuery({ queryKey: ['admin-appointment-blocks'], queryFn: async () => (await apiClient.get<ApiResponse<Block[]>>('/admin/appointment-blocks')).data.data })
  if (appointments.isLoading || options.isLoading) return <LoadingState />

  const refresh = async (key: string) => client.invalidateQueries({ queryKey: [key] })
  const action = async (item: Appointment, name: string) => { try { await apiClient.post(`/admin/appointments/${item.id}/${name}`); await refresh('admin-appointments'); toast.success('Đã cập nhật lịch hẹn.') } catch { toast.error('Chuyển trạng thái không hợp lệ.') } }
  const submitFilters = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSearchParams(Object.fromEntries([...new FormData(event.currentTarget).entries()].filter(([, value]) => value !== '')) as Record<string, string>) }
  const reschedule = async () => { if (!rescheduleId || !rescheduleAt) return; try { await apiClient.patch(`/admin/appointments/${rescheduleId}/reschedule`, { start_at: new Date(rescheduleAt).toISOString() }); await refresh('admin-appointments'); setRescheduleId(null); setRescheduleAt(''); toast.success('Đã đổi lịch.') } catch { toast.error('Khung giờ mới không khả dụng.') } }
  const createSchedule = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const raw = Object.fromEntries(new FormData(event.currentTarget).entries()); try { await apiClient.post('/admin/appointment-schedules', { ...raw, branch_id: Number(raw.branch_id), day_of_week: Number(raw.day_of_week), slot_minutes: Number(raw.slot_minutes), capacity: Number(raw.capacity), is_active: true }); await refresh('admin-appointment-schedules'); event.currentTarget.reset(); toast.success('Đã tạo lịch làm việc.') } catch { toast.error('Lịch bị trùng hoặc chưa hợp lệ.') } }
  const createBlock = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const raw = Object.fromEntries(new FormData(event.currentTarget).entries()); try { await apiClient.post('/admin/appointment-blocks', { branch_id: Number(raw.branch_id), start_at: new Date(String(raw.start_at)).toISOString(), end_at: new Date(String(raw.end_at)).toISOString(), reason: raw.reason || null }); await refresh('admin-appointment-blocks'); event.currentTarget.reset(); toast.success('Đã chặn khoảng thời gian.') } catch { toast.error('Khoảng chặn chưa hợp lệ.') } }
  const remove = async (kind: 'appointment-schedules' | 'appointment-blocks', id: number) => { try { await apiClient.delete(`/admin/${kind}/${id}`); await refresh(`admin-${kind}`); toast.success('Đã xóa.') } catch { toast.error('Không thể xóa dữ liệu.') } }

  return <div>
    <div className='mb-6 flex flex-wrap items-center justify-between gap-3'><div><h1 className='text-3xl font-black'>Lịch hẹn</h1><p className='muted'>Quản lý booking, capacity, lịch làm việc và khoảng chặn.</p></div><div className='flex flex-wrap gap-2'><TabButton active={tab === 'list'} onClick={() => setTab('list')}>Danh sách</TabButton><TabButton active={tab === 'schedule'} onClick={() => setTab('schedule')}>Lịch làm việc</TabButton><TabButton active={tab === 'blocks'} onClick={() => setTab('blocks')}>Khoảng chặn</TabButton></div></div>
    {tab === 'list' && <>
      <form className='card mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-7' onSubmit={submitFilters}><input className='input' type='date' name='date' defaultValue={filters.date} aria-label='Ngày lịch hẹn' /><select className='input' name='branch_id' defaultValue={filters.branch_id} aria-label='Chi nhánh'><option value=''>Tất cả chi nhánh</option>{options.data?.branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className='input' name='service_id' defaultValue={filters.service_id} aria-label='Dịch vụ'><option value=''>Tất cả dịch vụ</option>{options.data?.services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className='input' name='status' defaultValue={filters.status} aria-label='Trạng thái'><option value=''>Tất cả trạng thái</option>{['pending', 'confirmed', 'checked_in', 'completed', 'cancelled', 'no_show'].map((status) => <option key={status} value={status}>{statusLabel[status] ?? status}</option>)}</select><input className='input' name='customer' defaultValue={filters.customer} placeholder='Khách hàng' aria-label='Khách hàng' /><input className='input' name='phone' defaultValue={filters.phone} placeholder='Số điện thoại' aria-label='Số điện thoại' /><button className='btn-primary'>Lọc</button></form>
      {appointments.data?.data.length ? <div className='grid gap-4'>{appointments.data.data.map((item) => <article className='card p-5' key={item.id}><div className='flex flex-wrap justify-between gap-3'><div><strong>{item.code} · {item.customer_name}</strong><p className='muted'>{new Date(item.start_at).toLocaleString('vi-VN')} · {item.service.name} · {item.branch.name}</p><p className='muted'>{item.customer_phone}</p></div><span className='badge'>{statusLabel[item.status] ?? item.status}</span></div><div className='mt-4 flex flex-wrap gap-2'><button className='btn-secondary' onClick={() => downloadAppointmentIcs(item)}><CalendarPlus size={16} />Thêm vào lịch</button>{canManage && <>{item.status === 'pending' && <button className='btn-primary' onClick={() => void action(item, 'confirm')}>Xác nhận</button>}{item.status === 'confirmed' && <><button className='btn-primary' onClick={() => void action(item, 'check-in')}>Check-in</button><button className='btn-secondary' onClick={() => void action(item, 'no-show')}>Không đến</button></>}{item.status === 'checked_in' && <button className='btn-primary' onClick={() => void action(item, 'complete')}>Hoàn tất</button>}{['pending', 'confirmed'].includes(item.status) && <><button className='btn-secondary' onClick={() => setRescheduleId(item.id)}>Đổi lịch</button><button className='btn-secondary text-red-700' onClick={() => void action(item, 'cancel')}>Hủy lịch</button></>}</>}</div>{rescheduleId === item.id && <div className='mt-4 flex flex-wrap items-end gap-2 rounded-xl bg-slate-50 p-4'><label><span className='label'>Thời gian mới</span><input className='input' type='datetime-local' value={rescheduleAt} onChange={(event) => setRescheduleAt(event.target.value)} /></label><button className='btn-primary' disabled={!rescheduleAt} onClick={() => void reschedule()}>Lưu đổi lịch</button><button className='btn-secondary' onClick={() => setRescheduleId(null)}>Đóng</button></div>}</article>)}</div> : <EmptyState title='Không có lịch hẹn' description='Không tìm thấy lịch phù hợp bộ lọc.' />}
    </>}
    {tab === 'schedule' && <div className={canManageSchedule ? 'grid gap-6 lg:grid-cols-[360px_1fr]' : ''}>{canManageSchedule && <form className='card grid gap-4 p-5' onSubmit={createSchedule}><h2 className='text-xl font-black'>Thêm lịch làm việc</h2><select className='input' name='branch_id' required><option value=''>Chi nhánh</option>{options.data?.branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className='input' name='day_of_week'>{weekdays.map((label, value) => <option key={label} value={value}>{label}</option>)}</select><input className='input' name='start_time' type='time' defaultValue='09:00' required /><input className='input' name='end_time' type='time' defaultValue='18:00' required /><input className='input' name='slot_minutes' type='number' defaultValue='30' min='5' max='720' required /><input className='input' name='capacity' type='number' defaultValue='1' min='1' max='100' required /><button className='btn-primary'>Lưu lịch</button></form>}<div className='table-wrap'><table className='table'><thead><tr><th>Chi nhánh</th><th>Ngày</th><th>Giờ</th><th>Slot</th><th>Capacity</th><th></th></tr></thead><tbody>{schedules.data?.map((item) => <tr key={item.id}><td>{options.data?.branches.find((branch) => branch.id === item.branch_id)?.name}</td><td>{weekdays[item.day_of_week]}</td><td>{item.start_time} - {item.end_time}</td><td>{item.slot_minutes} phút</td><td>{item.capacity}</td><td>{canManageSchedule && <button className='btn-secondary text-red-700' onClick={() => void remove('appointment-schedules', item.id)}>Xóa</button>}</td></tr>)}</tbody></table></div></div>}
    {tab === 'blocks' && <div className={canManageSchedule ? 'grid gap-6 lg:grid-cols-[360px_1fr]' : ''}>{canManageSchedule && <form className='card grid gap-4 p-5' onSubmit={createBlock}><h2 className='text-xl font-black'>Chặn thời gian</h2><select className='input' name='branch_id' required><option value=''>Chi nhánh</option>{options.data?.branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label><span className='label'>Bắt đầu</span><input className='input' name='start_at' type='datetime-local' required /></label><label><span className='label'>Kết thúc</span><input className='input' name='end_at' type='datetime-local' required /></label><textarea className='input min-h-24' name='reason' placeholder='Lý do' /><button className='btn-primary'>Lưu khoảng chặn</button></form>}<div className='table-wrap'><table className='table'><thead><tr><th>Chi nhánh</th><th>Bắt đầu</th><th>Kết thúc</th><th>Lý do</th><th></th></tr></thead><tbody>{blocks.data?.map((item) => <tr key={item.id}><td>{options.data?.branches.find((branch) => branch.id === item.branch_id)?.name}</td><td>{new Date(item.start_at).toLocaleString('vi-VN')}</td><td>{new Date(item.end_at).toLocaleString('vi-VN')}</td><td>{item.reason || '-'}</td><td>{canManageSchedule && <button className='btn-secondary text-red-700' onClick={() => void remove('appointment-blocks', item.id)}>Xóa</button>}</td></tr>)}</tbody></table></div></div>}
  </div>
}

function TabButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button className={active ? 'btn-primary' : 'btn-secondary'} type='button' onClick={onClick}>{children}</button> }
