import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Edit3, Plus, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { EmptyState } from '../../components/common/EmptyState'
import { LoadingState } from '../../components/common/LoadingState'
import type { AdminAttribute, AdminAttributeValue, ApiResponse } from '../../types'

type AttributeDraft = Partial<AdminAttribute>
type ValueDraft = Partial<AdminAttributeValue> & { attributeId: number }

export function AttributesAdminPage() {
  const client = useQueryClient()
  const [draft, setDraft] = useState<AttributeDraft | null>(null)
  const [valueDraft, setValueDraft] = useState<ValueDraft | null>(null)
  const query = useQuery({ queryKey: ['admin-attributes'], queryFn: async () => (await apiClient.get<ApiResponse<AdminAttribute[]>>('/admin/attributes')).data.data })
  const refresh = () => client.invalidateQueries({ queryKey: ['admin-attributes'] })
  const saveAttribute = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { name: String(form.get('name') ?? ''), code: String(form.get('code') ?? ''), type: String(form.get('type') ?? 'select'), is_filterable: form.get('is_filterable') === 'on', is_variant_attribute: form.get('is_variant_attribute') === 'on', is_active: form.get('is_active') === 'on' }; try { if (draft?.id) await apiClient.put(`/admin/attributes/${draft.id}`, payload); else await apiClient.post('/admin/attributes', payload); await refresh(); setDraft(null); toast.success('Đã lưu thuộc tính.') } catch { toast.error('Không thể lưu thuộc tính. Vui lòng kiểm tra mã không trùng.') } }
  const saveValue = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!valueDraft) return; const form = new FormData(event.currentTarget); const payload = { value: String(form.get('value') ?? ''), display_value: String(form.get('display_value') ?? ''), color_code: String(form.get('color_code') ?? '') || null, sort_order: Number(form.get('sort_order') ?? 0), is_active: form.get('is_active') === 'on' }; try { if (valueDraft.id) await apiClient.put(`/admin/attributes/${valueDraft.attributeId}/values/${valueDraft.id}`, payload); else await apiClient.post(`/admin/attributes/${valueDraft.attributeId}/values`, payload); await refresh(); setValueDraft(null); toast.success('Đã lưu giá trị thuộc tính.') } catch { toast.error('Không thể lưu giá trị thuộc tính.') } }
  const removeAttribute = async (id: number) => { if (!confirm('Xóa thuộc tính và toàn bộ giá trị?')) return; try { await apiClient.delete(`/admin/attributes/${id}`); await refresh(); toast.success('Đã xóa thuộc tính.') } catch { toast.error('Không thể xóa thuộc tính đang được sử dụng.') } }
  const removeValue = async (attributeId: number, id: number) => { if (!confirm('Xóa giá trị thuộc tính này?')) return; try { await apiClient.delete(`/admin/attributes/${attributeId}/values/${id}`); await refresh(); toast.success('Đã xóa giá trị.') } catch { toast.error('Không thể xóa giá trị đang được sử dụng.') } }
  return <div><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Thuộc tính</h1><p className="muted">Quản lý màu, chiều dài, mật độ, kích thước và loại đế.</p></div><button className="btn-primary" onClick={() => setDraft({ type: 'select', is_filterable: true, is_variant_attribute: true, is_active: true })}><Plus size={18} />Thêm thuộc tính</button></div>
    {draft && <form className="card mb-6 grid gap-4 p-5 md:grid-cols-3" onSubmit={saveAttribute}><label><span className="label">Tên thuộc tính</span><input className="input" name="name" defaultValue={draft.name} required /></label><label><span className="label">Mã</span><input className="input" name="code" defaultValue={draft.code} placeholder="hair_color" required /></label><label><span className="label">Kiểu dữ liệu</span><select className="input" name="type" defaultValue={draft.type ?? 'select'}><option value="select">Danh sách</option><option value="color">Màu sắc</option><option value="text">Văn bản</option></select></label><label className="flex items-center gap-2"><input type="checkbox" name="is_filterable" defaultChecked={draft.is_filterable ?? true} /> Dùng để lọc</label><label className="flex items-center gap-2"><input type="checkbox" name="is_variant_attribute" defaultChecked={draft.is_variant_attribute ?? true} /> Dùng cho biến thể</label><label className="flex items-center gap-2"><input type="checkbox" name="is_active" defaultChecked={draft.is_active ?? true} /> Đang hoạt động</label><div className="flex gap-2 md:col-span-3"><button className="btn-primary">Lưu thuộc tính</button><button type="button" className="btn-secondary" onClick={() => setDraft(null)}><X size={17} />Đóng</button></div></form>}
    {valueDraft && <form className="card mb-6 grid gap-4 p-5 md:grid-cols-4" onSubmit={saveValue}><label><span className="label">Giá trị hệ thống</span><input className="input" name="value" defaultValue={valueDraft.value} required /></label><label><span className="label">Tên hiển thị</span><input className="input" name="display_value" defaultValue={valueDraft.display_value} required /></label><label><span className="label">Mã màu</span><input className="input" name="color_code" defaultValue={valueDraft.color_code ?? ''} placeholder="#1f2937" /></label><label><span className="label">Thứ tự</span><input className="input" name="sort_order" type="number" min="0" defaultValue={valueDraft.sort_order ?? 0} /></label><label className="flex items-center gap-2"><input type="checkbox" name="is_active" defaultChecked={valueDraft.is_active ?? true} /> Đang hoạt động</label><div className="flex gap-2 md:col-span-3"><button className="btn-primary">Lưu giá trị</button><button type="button" className="btn-secondary" onClick={() => setValueDraft(null)}><X size={17} />Đóng</button></div></form>}
    {query.isLoading ? <LoadingState /> : query.data?.length ? <div className="grid gap-5 lg:grid-cols-2">{query.data.map((attribute) => <section className="card p-5" key={attribute.id}><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-black">{attribute.name}</h2><p className="muted text-sm">{attribute.code} · {attribute.type} · {attribute.is_active ? 'Đang dùng' : 'Đã ẩn'}</p></div><div className="flex gap-2"><button className="btn-secondary px-3" onClick={() => setDraft(attribute)} aria-label={`Sửa ${attribute.name}`}><Edit3 size={16} /></button><button className="btn-secondary px-3 text-red-700" onClick={() => removeAttribute(attribute.id)} aria-label={`Xóa ${attribute.name}`}><Trash2 size={16} /></button></div></div><div className="mt-4 grid gap-2">{attribute.values.map((value) => <div key={value.id} className="flex items-center justify-between rounded-xl border p-3"><div className="flex items-center gap-3">{value.color_code && <span className="h-6 w-6 rounded-full border" style={{ background: value.color_code }} />}<div><strong>{value.display_value}</strong><div className="text-xs text-slate-500">{value.value}</div></div></div><div className="flex gap-2"><button className="btn-secondary px-3" onClick={() => setValueDraft({ ...value, attributeId: attribute.id })}><Edit3 size={15} /></button><button className="btn-secondary px-3 text-red-700" onClick={() => removeValue(attribute.id, value.id)}><Trash2 size={15} /></button></div></div>)}</div><button className="btn-secondary mt-4" onClick={() => setValueDraft({ attributeId: attribute.id, sort_order: attribute.values.length, is_active: true })}><Plus size={16} />Thêm giá trị</button></section>)}</div> : <EmptyState title="Chưa có thuộc tính" description="Tạo thuộc tính đầu tiên để cấu hình biến thể sản phẩm." />}
  </div>
}
