import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Edit3, Plus, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { LoadingState } from '../../components/common/LoadingState'
import type { AdminAttribute, AdminAttributeValue, ApiResponse } from '../../types'

type AttributeDraft = Partial<AdminAttribute>
type ValueDraft = Partial<AdminAttributeValue> & { attributeId: number }

export function AttributesAdminPage() {
  const client = useQueryClient()
  const [draft, setDraft] = useState<AttributeDraft | null>(null)
  const [valueDraft, setValueDraft] = useState<ValueDraft | null>(null)
  const query = useQuery({ queryKey: ['admin-attributes'], queryFn: async () => (await apiClient.get<ApiResponse<AdminAttribute[]>>('/admin/attributes')).data.data })
  const refresh = () => client.invalidateQueries({ queryKey: ['admin-attributes'] })
  const saveAttribute = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    const payload = { name: String(form.get('name') ?? ''), code: String(form.get('code') ?? ''), type: String(form.get('type') ?? 'select'), display_style: String(form.get('display_style') ?? '') || null, sort_order: Number(form.get('sort_order') ?? 0), is_filterable: form.get('is_filterable') === 'on', is_variant_attribute: form.get('is_variant_attribute') === 'on', is_active: form.get('is_active') === 'on' }
    try { if (draft?.id) await apiClient.put('/admin/attributes/' + draft.id, payload); else await apiClient.post('/admin/attributes', payload); await refresh(); setDraft(null); toast.success('Đã lưu thuộc tính.') } catch { toast.error('Không thể lưu thuộc tính.') }
  }
  const saveValue = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!valueDraft) return
    const form = new FormData(event.currentTarget)
    const payload = { value: String(form.get('value') ?? ''), display_value: String(form.get('display_value') ?? ''), option_code: String(form.get('option_code') ?? '') || null, description: String(form.get('description') ?? '') || null, color_code: String(form.get('color_code') ?? '') || null, image_alt: String(form.get('image_alt') ?? '') || null, sort_order: Number(form.get('sort_order') ?? 0), is_active: form.get('is_active') === 'on' }
    try {
      const response = valueDraft.id ? await apiClient.put<ApiResponse<AdminAttributeValue>>('/admin/attributes/' + valueDraft.attributeId + '/values/' + valueDraft.id, payload) : await apiClient.post<ApiResponse<AdminAttributeValue>>('/admin/attributes/' + valueDraft.attributeId + '/values', payload)
      const image = form.get('image')
      if (image instanceof File && image.size) { const media = new FormData(); media.append('image', image); await apiClient.post('/admin/attributes/' + valueDraft.attributeId + '/values/' + response.data.data.id + '/image', media) }
      await refresh(); setValueDraft(null); toast.success('Đã lưu giá trị thuộc tính.')
    } catch { toast.error('Không thể lưu giá trị thuộc tính.') }
  }
  const removeAttribute = async (id: number) => { if (!confirm('Xóa thuộc tính và toàn bộ giá trị?')) return; try { await apiClient.delete('/admin/attributes/' + id); await refresh() } catch { toast.error('Không thể xóa thuộc tính đang được sử dụng.') } }
  const removeValue = async (attributeId: number, id: number) => { if (!confirm('Xóa giá trị thuộc tính này?')) return; try { await apiClient.delete('/admin/attributes/' + attributeId + '/values/' + id); await refresh() } catch { toast.error('Không thể xóa giá trị đang được sử dụng.') } }
  if (query.isLoading) return <LoadingState />
  return <div><div className='mb-6 flex items-center justify-between gap-3'><div><h1 className='text-3xl font-black'>Thuộc tính</h1><p className='muted'>Quản lý cách hiển thị, media và thứ tự option.</p></div><button className='btn-primary' onClick={() => setDraft({ type: 'select', display_style: 'buttons', sort_order: 0, is_filterable: true, is_variant_attribute: true, is_active: true })}><Plus size={18} />Thêm thuộc tính</button></div>
    {draft && <form className='card mb-6 grid gap-4 p-5 md:grid-cols-4' onSubmit={saveAttribute}><label><span className='label'>Tên thuộc tính</span><input className='input' name='name' defaultValue={draft.name} required /></label><label><span className='label'>Mã</span><input className='input' name='code' defaultValue={draft.code} required /></label><label><span className='label'>Kiểu dữ liệu</span><select className='input' name='type' defaultValue={draft.type ?? 'select'}><option value='select'>Danh sách</option><option value='color'>Màu sắc</option><option value='text'>Văn bản</option></select></label><label><span className='label'>Hiển thị</span><select className='input' name='display_style' defaultValue={draft.display_style ?? ''}><option value=''>Tự động</option><option value='buttons'>Nút</option><option value='image_swatches'>Swatch ảnh</option><option value='image_cards'>Thẻ ảnh</option></select></label><label><span className='label'>Thứ tự</span><input className='input' type='number' min='0' name='sort_order' defaultValue={draft.sort_order ?? 0} /></label>{['is_filterable', 'is_variant_attribute', 'is_active'].map((name) => <label className='flex items-center gap-2' key={name}><input type='checkbox' name={name} defaultChecked={Boolean(draft[name as keyof AttributeDraft])} />{name === 'is_filterable' ? 'Dùng để lọc' : name === 'is_variant_attribute' ? 'Dùng cho biến thể' : 'Hoạt động'}</label>)}<div className='flex gap-2 md:col-span-4'><button className='btn-primary'>Lưu thuộc tính</button><button type='button' className='btn-secondary' onClick={() => setDraft(null)}><X size={16} />Hủy</button></div></form>}
    {valueDraft && <form className='card mb-6 grid gap-4 p-5 md:grid-cols-3' onSubmit={saveValue}><label><span className='label'>Giá trị</span><input className='input' name='value' defaultValue={valueDraft.value} required /></label><label><span className='label'>Tên hiển thị</span><input className='input' name='display_value' defaultValue={valueDraft.display_value} required /></label><label><span className='label'>Mã option</span><input className='input' name='option_code' defaultValue={valueDraft.option_code ?? ''} /></label><label><span className='label'>Mã màu</span><input className='input' name='color_code' defaultValue={valueDraft.color_code ?? ''} /></label><label><span className='label'>Alt ảnh</span><input className='input' name='image_alt' defaultValue={valueDraft.image_alt ?? ''} /></label><label><span className='label'>Ảnh option</span><input className='input' type='file' name='image' accept='image/jpeg,image/png,image/webp' /></label><label><span className='label'>Thứ tự</span><input className='input' type='number' min='0' name='sort_order' defaultValue={valueDraft.sort_order ?? 0} /></label><label className='md:col-span-2'><span className='label'>Mô tả</span><textarea className='input' name='description' defaultValue={valueDraft.description ?? ''} /></label><label className='flex items-center gap-2'><input type='checkbox' name='is_active' defaultChecked={valueDraft.is_active ?? true} />Hoạt động</label><div className='flex gap-2 md:col-span-3'><button className='btn-primary'>Lưu giá trị</button><button type='button' className='btn-secondary' onClick={() => setValueDraft(null)}>Hủy</button></div></form>}
    <div className='grid gap-5'>{query.data?.map((attribute) => <section className='card p-5' key={attribute.id}><div className='flex flex-wrap items-center justify-between gap-3'><div><h2 className='text-xl font-black'>{attribute.name}</h2><p className='muted'>{attribute.code} · {attribute.display_style || 'auto'} · thứ tự {attribute.sort_order}</p></div><div className='flex gap-2'><button className='btn-secondary' onClick={() => setDraft(attribute)}><Edit3 size={16} />Sửa</button><button className='btn-secondary text-red-700' aria-label={'Xóa ' + attribute.name} onClick={() => removeAttribute(attribute.id)}><Trash2 size={16} />Xóa</button></div></div><div className='mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3'>{attribute.values.map((value) => <article className='rounded-xl border p-3' key={value.id}><div className='flex gap-3'>{value.image_url && <img src={value.image_url} alt={value.image_alt || value.display_value} className='h-16 w-16 rounded-lg object-cover' />}<div><strong>{value.display_value}</strong>{value.option_code && <span className='ml-2 text-sm'>({value.option_code})</span>}<p className='muted text-sm'>{value.description}</p></div></div><div className='mt-3 flex gap-2'><button className='btn-secondary px-3 py-2 text-sm' onClick={() => setValueDraft({ ...value, attributeId: attribute.id })}>Sửa</button><button className='btn-secondary px-3 py-2 text-sm text-red-700' onClick={() => removeValue(attribute.id, value.id)}>Xóa</button></div></article>)}<button className='rounded-xl border border-dashed p-4 font-bold' onClick={() => setValueDraft({ attributeId: attribute.id, sort_order: attribute.values.length, is_active: true })}><Plus size={17} className='inline' /> Thêm giá trị</button></div></section>)}</div>
  </div>
}
