import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Edit3, Plus, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { EmptyState } from '../../components/common/EmptyState'
import { LoadingState } from '../../components/common/LoadingState'
import type { ApiResponse, Branch } from '../../types'

export function BranchesAdminPage() {
  const client = useQueryClient(); const [draft, setDraft] = useState<Partial<Branch> | null>(null)
  const query = useQuery({ queryKey: ['admin-branches'], queryFn: async () => (await apiClient.get<ApiResponse<Branch[]>>('/admin/branches')).data.data })
  const refresh = () => client.invalidateQueries({ queryKey: ['admin-branches'] })
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { name: String(form.get('name') ?? ''), code: String(form.get('code') ?? ''), phone: String(form.get('phone') ?? '') || null, email: String(form.get('email') ?? '') || null, province: String(form.get('province') ?? '') || null, district: String(form.get('district') ?? '') || null, ward: String(form.get('ward') ?? '') || null, address_line: String(form.get('address_line') ?? '') || null, is_default: form.get('is_default') === 'on', is_active: form.get('is_active') === 'on' }; try { if (draft?.id) await apiClient.put(`/admin/branches/${draft.id}`, payload); else await apiClient.post('/admin/branches', payload); await refresh(); setDraft(null); toast.success('Đã lưu chi nhánh.') } catch { toast.error('Không thể lưu chi nhánh. Vui lòng kiểm tra mã và email.') } }
  const remove = async (branch: Branch) => { if (!confirm(`Xóa chi nhánh ${branch.name}?`)) return; try { await apiClient.delete(`/admin/branches/${branch.id}`); await refresh(); toast.success('Đã xóa chi nhánh.') } catch { toast.error('Không thể xóa chi nhánh mặc định hoặc đang có tồn kho.') } }
  return <div><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Chi nhánh</h1><p className="muted">Quản lý địa điểm phục vụ và kho hàng.</p></div><button className="btn-primary" onClick={() => setDraft({ is_active: true, is_default: false })}><Plus size={18} />Thêm chi nhánh</button></div>
    {draft && <form className="card mb-6 grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4" onSubmit={save}><label><span className="label">Tên chi nhánh</span><input className="input" name="name" defaultValue={draft.name} required /></label><label><span className="label">Mã chi nhánh</span><input className="input" name="code" defaultValue={draft.code} required /></label><label><span className="label">Điện thoại</span><input className="input" name="phone" defaultValue={draft.phone ?? ''} /></label><label><span className="label">Email</span><input className="input" name="email" type="email" defaultValue={draft.email ?? ''} /></label><label><span className="label">Tỉnh / thành</span><input className="input" name="province" defaultValue={draft.province ?? ''} /></label><label><span className="label">Quận / huyện</span><input className="input" name="district" defaultValue={draft.district ?? ''} /></label><label><span className="label">Phường / xã</span><input className="input" name="ward" defaultValue={draft.ward ?? ''} /></label><label><span className="label">Địa chỉ</span><input className="input" name="address_line" defaultValue={draft.address_line ?? ''} /></label><label className="flex items-center gap-2"><input type="checkbox" name="is_default" defaultChecked={draft.is_default} /> Chi nhánh mặc định</label><label className="flex items-center gap-2"><input type="checkbox" name="is_active" defaultChecked={draft.is_active ?? true} /> Đang hoạt động</label><div className="flex gap-2 md:col-span-2"><button className="btn-primary">Lưu chi nhánh</button><button type="button" className="btn-secondary" onClick={() => setDraft(null)}><X size={17} />Đóng</button></div></form>}
    {query.isLoading ? <LoadingState /> : query.data?.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Chi nhánh</th><th>Liên hệ</th><th>Địa chỉ</th><th>Vai trò</th><th>Trạng thái</th><th></th></tr></thead><tbody>{query.data.map((branch) => <tr key={branch.id}><td><strong>{branch.name}</strong><div className="text-sm text-slate-500">{branch.code}</div></td><td>{branch.phone || '—'}<div className="text-sm text-slate-500">{branch.email}</div></td><td>{[branch.address_line, branch.ward, branch.district, branch.province].filter(Boolean).join(', ') || '—'}</td><td>{branch.is_default ? 'Mặc định' : 'Phụ'}</td><td>{branch.is_active ? 'Hoạt động' : 'Tạm ngưng'}</td><td><div className="flex gap-2"><button className="btn-secondary px-3" onClick={() => setDraft(branch)}><Edit3 size={16} /></button><button className="btn-secondary px-3 text-red-700" onClick={() => remove(branch)}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState title="Chưa có chi nhánh" description="Tạo chi nhánh để bắt đầu quản lý tồn kho." />}</div>
}
