import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Edit3, Plus, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { EmptyState } from '../../components/common/EmptyState'
import { LoadingState } from '../../components/common/LoadingState'
import type { ApiResponse, Coupon, Pagination } from '../../types'
import { useFormatPrice } from '../../utils/format'

const dateTimeValue = (value?: string | null) => value ? new Date(value).toISOString().slice(0, 16) : ''

export function CouponsAdminPage() {
  const formatPrice = useFormatPrice()
  const client = useQueryClient()
  const [draft, setDraft] = useState<Partial<Coupon> | null>(null)
  const query = useQuery({ queryKey: ['admin-coupons'], queryFn: async () => (await apiClient.get<ApiResponse<Pagination<Coupon>>>('/admin/coupons')).data.data })
  const refresh = () => client.invalidateQueries({ queryKey: ['admin-coupons'] })
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const nullableNumber = (name: string) => form.get(name) === '' ? null : Number(form.get(name)); const payload = { code: String(form.get('code') ?? '').toUpperCase(), type: String(form.get('type') ?? 'fixed'), value: Number(form.get('value')), minimum_order_amount: nullableNumber('minimum_order_amount'), maximum_discount_amount: nullableNumber('maximum_discount_amount'), usage_limit: nullableNumber('usage_limit'), usage_limit_per_user: nullableNumber('usage_limit_per_user'), starts_at: String(form.get('starts_at') ?? '') || null, expires_at: String(form.get('expires_at') ?? '') || null, is_active: form.get('is_active') === 'on' }; try { if (draft?.id) await apiClient.put(`/admin/coupons/${draft.id}`, payload); else await apiClient.post('/admin/coupons', payload); await refresh(); setDraft(null); toast.success('Đã lưu mã giảm giá.') } catch { toast.error('Không thể lưu mã. Kiểm tra mã trùng, giá trị và thời gian áp dụng.') } }
  const remove = async (coupon: Coupon) => { if (!confirm(`Xóa mã ${coupon.code}?`)) return; await apiClient.delete(`/admin/coupons/${coupon.id}`); await refresh(); toast.success('Đã xóa mã giảm giá.') }
  return <div><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Mã giảm giá</h1><p className="muted">Quản lý điều kiện, thời hạn và giới hạn sử dụng.</p></div><button className="btn-primary" onClick={() => setDraft({ type: 'percentage', is_active: true })}><Plus size={18} />Thêm mã</button></div>
    {draft && <form className="card mb-6 grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4" onSubmit={save}><label><span className="label">Mã</span><input className="input uppercase" name="code" defaultValue={draft.code} required /></label><label><span className="label">Loại giảm</span><select className="input" name="type" defaultValue={draft.type ?? 'percentage'}><option value="percentage">Phần trăm</option><option value="fixed">Số tiền</option></select></label><label><span className="label">Giá trị</span><input className="input" type="number" min="0" step="0.01" name="value" defaultValue={draft.value} required /></label><label><span className="label">Đơn tối thiểu</span><input className="input" type="number" min="0" name="minimum_order_amount" defaultValue={draft.minimum_order_amount ?? ''} /></label><label><span className="label">Giảm tối đa</span><input className="input" type="number" min="0" name="maximum_discount_amount" defaultValue={draft.maximum_discount_amount ?? ''} /></label><label><span className="label">Tổng lượt dùng</span><input className="input" type="number" min="1" name="usage_limit" defaultValue={draft.usage_limit ?? ''} /></label><label><span className="label">Lượt / khách</span><input className="input" type="number" min="1" name="usage_limit_per_user" defaultValue={draft.usage_limit_per_user ?? ''} /></label><label><span className="label">Bắt đầu</span><input className="input" type="datetime-local" name="starts_at" defaultValue={dateTimeValue(draft.starts_at)} /></label><label><span className="label">Kết thúc</span><input className="input" type="datetime-local" name="expires_at" defaultValue={dateTimeValue(draft.expires_at)} /></label><label className="flex items-center gap-2"><input type="checkbox" name="is_active" defaultChecked={draft.is_active ?? true} /> Đang hoạt động</label><div className="flex gap-2 md:col-span-2"><button className="btn-primary">Lưu mã</button><button type="button" className="btn-secondary" onClick={() => setDraft(null)}><X size={17} />Đóng</button></div></form>}
    {query.isLoading ? <LoadingState /> : query.data?.data.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Mã</th><th>Ưu đãi</th><th>Điều kiện</th><th>Đã dùng</th><th>Thời hạn</th><th>Trạng thái</th><th></th></tr></thead><tbody>{query.data.data.map((coupon) => <tr key={coupon.id}><td className="font-black">{coupon.code}</td><td>{coupon.type === 'percentage' ? `${coupon.value}%` : formatPrice(coupon.value)}</td><td>{coupon.minimum_order_amount ? `Từ ${formatPrice(coupon.minimum_order_amount)}` : 'Không giới hạn'}</td><td>{coupon.used_count}{coupon.usage_limit ? ` / ${coupon.usage_limit}` : ''}</td><td>{coupon.expires_at ? new Date(coupon.expires_at).toLocaleDateString('vi-VN') : 'Không hết hạn'}</td><td>{coupon.is_active ? 'Hoạt động' : 'Tạm dừng'}</td><td><div className="flex gap-2"><button className="btn-secondary px-3" onClick={() => setDraft(coupon)}><Edit3 size={16} /></button><button className="btn-secondary px-3 text-red-700" onClick={() => remove(coupon)}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState title="Chưa có mã giảm giá" description="Tạo mã đầu tiên cho chương trình ưu đãi." />}
  </div>
}
