import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Ban, Eye, Search, ShieldCheck, X } from 'lucide-react'
import { useDeferredValue, useState } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { EmptyState } from '../../components/common/EmptyState'
import { LoadingState } from '../../components/common/LoadingState'
import type { AdminCustomer, ApiResponse, CustomerDetail, Pagination } from '../../types'
import { formatPrice, statusLabel } from '../../utils/format'

export function CustomersAdminPage() {
  const client = useQueryClient(); const [search, setSearch] = useState(''); const [selectedId, setSelectedId] = useState<number | null>(null); const deferredSearch = useDeferredValue(search)
  const query = useQuery({ queryKey: ['admin-customers', deferredSearch], queryFn: async () => (await apiClient.get<ApiResponse<Pagination<AdminCustomer>>>('/admin/customers', { params: { search: deferredSearch || undefined } })).data.data })
  const detail = useQuery({ queryKey: ['admin-customer', selectedId], enabled: selectedId !== null, queryFn: async () => (await apiClient.get<ApiResponse<CustomerDetail>>(`/admin/customers/${selectedId}`)).data.data })
  const changeStatus = async (customer: AdminCustomer | CustomerDetail) => { const status = customer.status === 'active' ? 'blocked' : 'active'; if (status === 'blocked' && !confirm(`Khóa tài khoản ${customer.name}?`)) return; await apiClient.patch(`/admin/customers/${customer.id}/status`, { status }); await Promise.all([client.invalidateQueries({ queryKey: ['admin-customers'] }), client.invalidateQueries({ queryKey: ['admin-customer', customer.id] })]); toast.success(status === 'active' ? 'Đã mở khóa khách hàng.' : 'Đã khóa khách hàng.') }
  return <div><div className="mb-6"><h1 className="text-3xl font-black">Khách hàng</h1><p className="muted">Tra cứu hồ sơ, đơn hàng và trạng thái tài khoản.</p></div><label className="relative mb-5 block max-w-xl"><Search className="absolute left-4 top-3.5 text-slate-400" size={18} /><input className="input pl-11" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm theo tên, email hoặc số điện thoại" /></label>
    {selectedId && <section className="card mb-6 p-5">{detail.isLoading || !detail.data ? <LoadingState label="Đang tải hồ sơ khách hàng..." /> : <><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">{detail.data.name}</h2><p className="muted">{detail.data.email} · {detail.data.phone || 'Chưa có số điện thoại'}</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={() => changeStatus(detail.data)}>{detail.data.status === 'active' ? <Ban size={17} /> : <ShieldCheck size={17} />}{detail.data.status === 'active' ? 'Khóa tài khoản' : 'Mở khóa'}</button><button className="btn-secondary px-3" onClick={() => setSelectedId(null)}><X size={17} /></button></div></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="font-black">Địa chỉ</h3><div className="mt-3 grid gap-2">{detail.data.addresses.length ? detail.data.addresses.map((address) => <div key={address.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{address.recipient_name} · {address.phone}</strong><div className="muted mt-1">{[address.address_line, address.ward, address.district, address.province].join(', ')}</div></div>) : <p className="muted">Chưa có địa chỉ.</p>}</div></div><div><h3 className="font-black">Đơn hàng gần đây</h3><div className="mt-3 grid gap-2">{detail.data.orders.length ? detail.data.orders.slice(0, 5).map((order) => <div key={order.id} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><div><strong>{order.order_number}</strong><div className="muted">{statusLabel[order.order_status]}</div></div><strong>{formatPrice(order.total_amount)}</strong></div>) : <p className="muted">Chưa có đơn hàng.</p>}</div></div></div></>}</section>}
    {query.isLoading ? <LoadingState /> : query.data?.data.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Khách hàng</th><th>Điện thoại</th><th>Số đơn</th><th>Trạng thái</th><th>Ngày tạo</th><th></th></tr></thead><tbody>{query.data.data.map((customer) => <tr key={customer.id}><td><strong>{customer.name}</strong><div className="text-sm text-slate-500">{customer.email}</div></td><td>{customer.phone || '—'}</td><td>{customer.orders_count}</td><td>{customer.status === 'active' ? 'Hoạt động' : 'Đã khóa'}</td><td>{new Date(customer.created_at).toLocaleDateString('vi-VN')}</td><td><div className="flex gap-2"><button className="btn-secondary px-3" onClick={() => setSelectedId(customer.id)} aria-label={`Xem ${customer.name}`}><Eye size={16} /></button><button className={`btn-secondary px-3 ${customer.status === 'active' ? 'text-red-700' : 'text-emerald-800'}`} onClick={() => changeStatus(customer)}>{customer.status === 'active' ? <Ban size={16} /> : <ShieldCheck size={16} />}</button></div></td></tr>)}</tbody></table></div> : <EmptyState title="Không tìm thấy khách hàng" description="Thử thay đổi từ khóa tìm kiếm." />}</div>
}
