import { useQuery } from '@tanstack/react-query'
import { BarChart3, CircleDollarSign, Package, ShoppingBag, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { apiClient } from '../../api/apiClient'
import { LoadingState } from '../../components/common/LoadingState'
import type { ApiResponse, AttentionSummary, InventoryRow } from '../../types'
import { formatPrice, statusLabel } from '../../utils/format'

interface Summary { revenue: number; orders: number; customers: number; products: number; average_order_value: number }
interface RevenuePoint { date: string; revenue: number; orders: number }
interface StatusPoint { order_status: string; total: number }
interface TopProduct { product_name: string; quantity: number; revenue: number }

export function DashboardPage() {
  const summary = useQuery({ queryKey: ['admin-summary'], queryFn: async ({ signal }) => (await apiClient.get<ApiResponse<Summary>>('/admin/dashboard/summary', { signal })).data.data })
  const revenue = useQuery({ queryKey: ['admin-revenue'], queryFn: async ({ signal }) => (await apiClient.get<ApiResponse<RevenuePoint[]>>('/admin/dashboard/revenue?days=30', { signal })).data.data })
  const statuses = useQuery({ queryKey: ['admin-statuses'], queryFn: async ({ signal }) => (await apiClient.get<ApiResponse<StatusPoint[]>>('/admin/dashboard/order-statuses', { signal })).data.data })
  const top = useQuery({ queryKey: ['admin-top'], queryFn: async ({ signal }) => (await apiClient.get<ApiResponse<TopProduct[]>>('/admin/dashboard/top-products', { signal })).data.data })
  const lowStock = useQuery({ queryKey: ['admin-low-stock'], queryFn: async ({ signal }) => (await apiClient.get<ApiResponse<InventoryRow[]>>('/admin/dashboard/low-stock', { signal })).data.data })
  const dashboardReady = [summary, revenue, statuses, top, lowStock].every((query) => !query.isLoading && !query.isFetching)
  const attention = useQuery({ queryKey: ['admin-attention'], queryFn: async ({ signal }) => (await apiClient.get<ApiResponse<AttentionSummary>>('/admin/dashboard/attention', { signal })).data.data, enabled: dashboardReady, staleTime: 60_000 })
  if (summary.isLoading) return <LoadingState />
  const cards = [[formatPrice(summary.data?.revenue ?? 0), 'Doanh thu', BarChart3], [summary.data?.orders ?? 0, 'Đơn hàng', ShoppingBag], [summary.data?.customers ?? 0, 'Khách hàng', Users], [summary.data?.products ?? 0, 'Sản phẩm', Package], [formatPrice(summary.data?.average_order_value ?? 0), 'Giá trị đơn trung bình', CircleDollarSign]] as const
  return <div><div className='mb-6'><h1 className='text-3xl font-black'>Dashboard</h1><p className='muted mt-1'>Tổng quan hoạt động kinh doanh từ dữ liệu thật.</p></div><section className='card mb-6 p-5'><h2 className='text-lg font-black'>Cần xử lý</h2><div className='mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4'>{attention.data?.items.map((item) => <Link className='rounded-xl border bg-slate-50 p-4 transition hover:border-emerald-400 hover:bg-emerald-50' to={item.url} key={item.key}><div className='text-2xl font-black text-emerald-800'>{item.count}</div><div className='mt-1 text-sm font-bold'>{item.label}</div></Link>)}</div></section><div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5'>{cards.map(([value, label, Icon]) => <div key={label} className='card flex min-w-0 items-center gap-4 p-5'><div className='grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-800'><Icon /></div><div className='min-w-0'><div className='break-words text-2xl font-black'>{value}</div><div className='muted text-sm'>{label}</div></div></div>)}</div>
    <div className='mt-6 grid gap-6 xl:grid-cols-3'><section className='card p-5 xl:col-span-2'><h2 className='text-lg font-black'>Doanh thu 30 ngày</h2><div className='mt-5 h-80'><ResponsiveContainer width='100%' height='100%'><LineChart data={revenue.data}><CartesianGrid strokeDasharray='3 3' /><XAxis dataKey='date' tick={{ fontSize: 12 }} /><YAxis tickFormatter={(value: number) => `${Math.round(value / 1000000)}tr`} /><Tooltip formatter={(value) => formatPrice(Number(value))} /><Line type='monotone' dataKey='revenue' stroke='#245c43' strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></div></section>
      <section className='card p-5'><h2 className='text-lg font-black'>Trạng thái đơn</h2><div className='mt-5 h-64'><ResponsiveContainer width='100%' height='100%'><PieChart><Pie data={statuses.data} dataKey='total' nameKey='order_status' innerRadius={55} outerRadius={85}>{statuses.data?.map((entry, index) => <Cell key={entry.order_status} fill={['#245c43', '#4f8b6b', '#e6a23c', '#5b7c99', '#7b5b9e', '#b85042'][index % 6]} />)}</Pie><Tooltip formatter={(value, name) => [value, statusLabel[String(name)] ?? name]} /></PieChart></ResponsiveContainer></div><div className='grid gap-2 text-sm'>{statuses.data?.map((item) => <div key={item.order_status} className='flex justify-between'><span>{statusLabel[item.order_status]}</span><strong>{item.total}</strong></div>)}</div></section>
    </div><section className='card mt-6 p-5'><h2 className='text-lg font-black'>Sản phẩm bán chạy</h2><div className='mt-5 h-72'><ResponsiveContainer width='100%' height='100%'><BarChart data={top.data} layout='vertical'><CartesianGrid strokeDasharray='3 3' /><XAxis type='number' /><YAxis type='category' dataKey='product_name' width={150} tick={{ fontSize: 12 }} /><Tooltip /><Bar dataKey='quantity' fill='#4f8b6b' radius={[0, 8, 8, 0]} /></BarChart></ResponsiveContainer></div></section>
    <section className='card mt-6 p-5'><div className='flex flex-wrap items-center justify-between gap-3'><div><h2 className='text-lg font-black'>Sản phẩm sắp hết hàng</h2><p className='muted mt-1 text-sm'>Các biến thể đã chạm hoặc xuống dưới ngưỡng đặt hàng lại.</p></div><Link className='font-bold text-emerald-800' to='/admin/inventory'>Xem tồn kho</Link></div>{lowStock.isLoading ? <div className='mt-5'><LoadingState label='Đang tải tồn kho thấp...' /></div> : lowStock.isError ? <div className='mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700'>Không thể tải danh sách tồn kho thấp.</div> : lowStock.data?.length ? <div className='table-wrap mt-5'><table className='table'><thead><tr><th>Sản phẩm</th><th>SKU</th><th>Chi nhánh</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Reorder level</th></tr></thead><tbody>{lowStock.data.map((row) => <tr key={row.id}><td className='font-bold'>{row.variant.product.name}</td><td>{row.variant.sku}</td><td>{row.branch.name}</td><td>{row.quantity_on_hand}</td><td>{row.quantity_reserved}</td><td className='font-bold text-amber-700'>{row.quantity_available ?? row.quantity_on_hand - row.quantity_reserved}</td><td>{row.reorder_level}</td></tr>)}</tbody></table></div> : <p className='muted mt-5'>Không có sản phẩm nào dưới ngưỡng tồn kho.</p>}</section>
  </div>
}
