import { FileDown, FileUp } from 'lucide-react'
import { useState, type ChangeEvent } from 'react'
import { toast } from 'sonner'
import * as XLSX from 'xlsx'
import { apiClient } from '../../api/apiClient'
import type { ApiResponse } from '../../types'
import { formatPrice } from '../../utils/format'

type JsonRecord = Record<string, string | number | boolean | null>
interface ImportRow { name?: string; base_sku?: string; category?: string; description?: string; material?: string; base_type?: string; variant_sku?: string; barcode?: string; price?: number; sale_price?: number; stock_quantity?: number; branch_code?: string; status?: string }
interface ImportResult { created: number; failed: number; errors: { row: number; message: string }[] }
const exportOptions = [['products', 'Sản phẩm'], ['orders', 'Đơn hàng'], ['inventory', 'Tồn kho'], ['customers', 'Khách hàng']] as const

export function ImportExportPage() {
  const [rows, setRows] = useState<ImportRow[]>([]); const [result, setResult] = useState<ImportResult | null>(null)
  const read = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { const workbook = XLSX.read(await file.arrayBuffer()); const sheet = workbook.Sheets[workbook.SheetNames[0]]; setRows(XLSX.utils.sheet_to_json<ImportRow>(sheet, { defval: '' })); setResult(null) } catch { toast.error('Không thể đọc file Excel.') } }
  const importRows = async () => { try { const response = await apiClient.post<ApiResponse<ImportResult>>('/admin/import/products', { rows }); setResult(response.data.data); toast.success('Đã xử lý dữ liệu import.') } catch { toast.error('File có dữ liệu chưa hợp lệ.') } }
  const downloadTemplate = () => { const data: ImportRow[] = [{ name: 'Hair System mẫu', base_sku: 'NH-MAU', category: 'Hair system nam', description: 'Mô tả sản phẩm', material: 'Tóc người thật', base_type: 'Đế lace', variant_sku: 'NH-MAU-01', barcode: '8930000000001', price: 1500000, sale_price: 1350000, stock_quantity: 10, branch_code: 'MAIN', status: 'active' }]; const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(data), 'products'); XLSX.writeFile(workbook, 'nam-hair-import-template.xlsx') }
  const exportData = async (resource: typeof exportOptions[number][0], label: string) => { try { const response = await apiClient.get<ApiResponse<JsonRecord[]>>(`/admin/export/${resource}`); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(response.data.data), resource); XLSX.writeFile(workbook, `nam-hair-${resource}-${new Date().toISOString().slice(0, 10)}.xlsx`); toast.success(`Đã export ${label.toLowerCase()}.`) } catch { toast.error(`Không thể export ${label.toLowerCase()}.`) } }
  return <div><div className="mb-6"><h1 className="text-3xl font-black">Import / Export Excel</h1><p className="muted">Nhập sản phẩm theo mẫu và xuất đầy đủ dữ liệu quản trị.</p></div><div className="grid gap-6 lg:grid-cols-2"><section className="card p-6"><h2 className="text-xl font-black">Import sản phẩm</h2><div className="mt-5 flex flex-wrap gap-3"><label className="btn-primary"><FileUp size={18} />Chọn file<input className="hidden" type="file" accept=".xlsx,.xls" onChange={read} /></label><button className="btn-secondary" onClick={downloadTemplate}>Tải file mẫu</button></div><p className="muted mt-3 text-sm">Đã đọc {rows.length} dòng, tối đa 500 dòng mỗi lần.</p>{rows.length > 0 && <><div className="table-wrap mt-5 max-h-72"><table className="table"><thead><tr><th>Dòng</th><th>Tên</th><th>SKU</th><th>Giá</th><th>Tồn</th></tr></thead><tbody>{rows.slice(0, 20).map((row, index) => <tr key={`${row.variant_sku}-${index}`}><td>{index + 2}</td><td>{row.name}</td><td>{row.variant_sku}</td><td>{formatPrice(row.price ?? 0)}</td><td>{row.stock_quantity}</td></tr>)}</tbody></table></div><button className="btn-primary mt-4" onClick={importRows}>Xác nhận import</button></>}{result && <div className="mt-4 rounded-xl bg-slate-50 p-4"><strong>Thành công: {result.created} · Lỗi: {result.failed}</strong>{result.errors.map((error) => <div key={`${error.row}-${error.message}`} className="mt-1 text-sm text-red-700">Dòng {error.row}: {error.message}</div>)}</div>}</section><section className="card p-6"><h2 className="text-xl font-black">Export dữ liệu</h2><p className="muted mt-2">Dữ liệu được lấy đầy đủ từ MySQL và tạo file xlsx tại trình duyệt.</p><div className="mt-5 grid gap-3">{exportOptions.map(([resource, label]) => <button key={resource} className="btn-secondary justify-start" onClick={() => exportData(resource, label)}><FileDown size={18} />Export {label.toLowerCase()}</button>)}</div></section></div></div>
}
