import { useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRightLeft } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { EmptyState } from '../../components/common/EmptyState'
import { LoadingState } from '../../components/common/LoadingState'
import type { ApiResponse, Branch, InventoryRow, InventoryTransaction, Pagination } from '../../types'

const transactionLabels: Record<string, string> = { import: 'Nhập kho', adjustment: 'Điều chỉnh', return: 'Hoàn hàng', transfer_in: 'Chuyển đến', transfer_out: 'Chuyển đi', sale: 'Bán hàng', sale_reserve: 'Giữ hàng', cancel_release: 'Hoàn tồn' }

export function InventoryTransactionsPage() {
  const client = useQueryClient(); const [branchId, setBranchId] = useState(''); const [type, setType] = useState('')
  const transactions = useQuery({ queryKey: ['admin-inventory-transactions', branchId, type], queryFn: async () => (await apiClient.get<ApiResponse<Pagination<InventoryTransaction>>>('/admin/inventory/transactions', { params: { branch_id: branchId || undefined, type: type || undefined } })).data.data })
  const branches = useQuery({ queryKey: ['admin-branches'], queryFn: async () => (await apiClient.get<ApiResponse<Branch[]>>('/admin/branches')).data.data })
  const inventory = useQuery({ queryKey: ['admin-inventory-transfer-source'], queryFn: async () => (await apiClient.get<ApiResponse<Pagination<InventoryRow>>>('/admin/inventory')).data.data })
  const transfer = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const source = inventory.data?.data.find((item) => item.id === Number(form.get('inventory_id'))); if (!source) return; try { await apiClient.post('/admin/inventory/transfer', { from_branch_id: source.branch_id, to_branch_id: Number(form.get('to_branch_id')), product_variant_id: source.product_variant_id, quantity: Number(form.get('quantity')), note: String(form.get('note') ?? '') || null }); await Promise.all([client.invalidateQueries({ queryKey: ['admin-inventory'] }), client.invalidateQueries({ queryKey: ['admin-inventory-transactions'] })]); formElement.reset(); toast.success('Đã chuyển kho thành công.') } catch { toast.error('Không thể chuyển kho. Kiểm tra chi nhánh và số lượng khả dụng.') } }
  return <div><div className="mb-6"><h1 className="text-3xl font-black">Lịch sử kho</h1><p className="muted">Theo dõi mọi biến động và thực hiện chuyển kho giữa các chi nhánh.</p></div><form className="card mb-6 grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-5" onSubmit={transfer}><label className="xl:col-span-2"><span className="label">Nguồn hàng</span><select className="input" name="inventory_id" required><option value="">Chọn sản phẩm / chi nhánh</option>{inventory.data?.data.filter((item) => item.quantity_available > 0).map((item) => <option key={item.id} value={item.id}>{item.variant.product.name} · {item.variant.sku} · {item.branch.name} ({item.quantity_available})</option>)}</select></label><label><span className="label">Chi nhánh nhận</span><select className="input" name="to_branch_id" required><option value="">Chọn chi nhánh</option>{branches.data?.filter((branch) => branch.is_active).map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><label><span className="label">Số lượng</span><input className="input" name="quantity" type="number" min="1" required /></label><button className="btn-primary self-end"><ArrowRightLeft size={17} />Chuyển kho</button><label className="md:col-span-2 xl:col-span-5"><span className="label">Ghi chú</span><input className="input" name="note" /></label></form><div className="mb-4 flex flex-wrap gap-3"><select className="input max-w-60" value={branchId} onChange={(event) => setBranchId(event.target.value)}><option value="">Tất cả chi nhánh</option>{branches.data?.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><select className="input max-w-52" value={type} onChange={(event) => setType(event.target.value)}><option value="">Tất cả nghiệp vụ</option>{Object.entries(transactionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
    {transactions.isLoading ? <LoadingState /> : transactions.data?.data.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Thời gian</th><th>Sản phẩm / SKU</th><th>Chi nhánh</th><th>Nghiệp vụ</th><th>Thay đổi</th><th>Trước → Sau</th><th>Ghi chú</th></tr></thead><tbody>{transactions.data.data.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString('vi-VN')}</td><td><strong>{item.variant.product.name}</strong><div className="text-sm text-slate-500">{item.variant.sku}</div></td><td>{item.branch.name}</td><td>{transactionLabels[item.type] ?? item.type}</td><td className={item.quantity > 0 ? 'font-black text-emerald-800' : 'font-black text-red-700'}>{item.quantity > 0 ? '+' : ''}{item.quantity}</td><td>{item.quantity_before} → {item.quantity_after}</td><td>{item.note || '—'}</td></tr>)}</tbody></table></div> : <EmptyState title="Chưa có giao dịch kho" description="Các thay đổi tồn kho sẽ xuất hiện tại đây." />}</div>
}
