import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { LoadingState } from '../../components/common/LoadingState'
import { PermissionGate } from '../../components/admin/PermissionGate'
import type { ApiResponse, Pagination } from '../../types'

interface InventoryRow { id: number; branch_id: number; product_variant_id: number; quantity_on_hand: number; quantity_reserved: number; quantity_available: number; reorder_level: number; branch: { id: number; name: string }; variant: { sku: string; product: { name: string } } }

export function InventoryAdminPage() {
  const client = useQueryClient(); const [selected, setSelected] = useState<InventoryRow | null>(null)
  const query = useQuery({ queryKey: ['admin-inventory'], queryFn: async () => (await apiClient.get<ApiResponse<Pagination<InventoryRow>>>('/admin/inventory')).data.data })
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const data = Object.fromEntries(new FormData(event.currentTarget).entries()); await apiClient.post('/admin/inventory/adjust', { ...data, branch_id: selected.branch_id, product_variant_id: selected.product_variant_id, quantity: Number(data.quantity) }); await client.invalidateQueries({ queryKey: ['admin-inventory'] }); setSelected(null); toast.success('Điều chỉnh kho thành công.') }
  return <div><div className="mb-6"><h1 className="text-3xl font-black">Tồn kho</h1><p className="muted">Theo dõi tồn thực, lượng giữ chỗ và cảnh báo sắp hết.</p></div>{selected && <PermissionGate permission="inventory.adjust"><form className="card mb-6 grid gap-4 p-5 md:grid-cols-4" onSubmit={submit}><div><span className="label">Biến thể</span><strong>{selected.variant.product.name} · {selected.variant.sku}</strong></div><input className="input" name="quantity" type="number" placeholder="+/- số lượng" required /><select className="input" name="type"><option value="adjustment">Điều chỉnh</option><option value="import">Nhập kho</option><option value="return">Hoàn hàng</option></select><button className="btn-primary">Xác nhận</button><input className="input md:col-span-4" name="note" placeholder="Ghi chú" /></form></PermissionGate>}{query.isLoading ? <LoadingState /> : <div className="table-wrap"><table className="table"><thead><tr><th>Sản phẩm / SKU</th><th>Chi nhánh</th><th>Tồn thực</th><th>Giữ chỗ</th><th>Khả dụng</th><th>Mức cảnh báo</th><th></th></tr></thead><tbody>{query.data?.data.map((item) => <tr key={item.id}><td><strong>{item.variant.product.name}</strong><div className="text-sm text-slate-500">{item.variant.sku}</div></td><td>{item.branch.name}</td><td>{item.quantity_on_hand}</td><td>{item.quantity_reserved}</td><td><span className={item.quantity_available <= item.reorder_level ? 'font-black text-red-700' : 'font-black text-emerald-800'}>{item.quantity_available}</span></td><td>{item.reorder_level}</td><td><PermissionGate permission="inventory.adjust" fallback={<span className="text-sm text-slate-400">Chỉ xem</span>}><button className="btn-secondary" onClick={() => setSelected(item)}>Điều chỉnh</button></PermissionGate></td></tr>)}</tbody></table></div>}</div>
}
