import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ExternalLink, Loader2, Save, TriangleAlert } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import { deleteNewsCtaImage, getAdminNewsPage, updateNewsPageContent, uploadNewsCtaImage } from '../../api/contentApi'
import { HomeImageCropEditor } from '../../components/admin/HomeImageCropEditor'
import { LoadingState } from '../../components/common/LoadingState'
import type { NewsPageContent } from '../../types'
import { resolveAssetUrl } from '../../utils/assetUrl'

const fallbackContent = {
  eyebrow: '', title: '', description: '', featured_badge_label: '', list_eyebrow: '', list_title: '', list_description: '',
  show_cta: false, cta_eyebrow: '', cta_title: '', cta_description: '', cta_primary_label: '', cta_primary_url: '', cta_secondary_label: '', cta_secondary_url: '', cta_image_alt: '',
}
type FormState = typeof fallbackContent & { featured_article_id: string; seo_title: string; seo_description: string }
const dateFormatter = new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit', year: 'numeric' })
const toFormState = (content?: NewsPageContent, seo?: { title?: string | null; description?: string | null }): FormState => ({ eyebrow: content?.eyebrow ?? fallbackContent.eyebrow, title: content?.title ?? fallbackContent.title, description: content?.description ?? fallbackContent.description, featured_badge_label: content?.featured_badge_label ?? fallbackContent.featured_badge_label, list_eyebrow: content?.list_eyebrow ?? fallbackContent.list_eyebrow, list_title: content?.list_title ?? fallbackContent.list_title, list_description: content?.list_description ?? fallbackContent.list_description, show_cta: content?.show_cta ?? fallbackContent.show_cta, cta_eyebrow: content?.cta_eyebrow ?? fallbackContent.cta_eyebrow, cta_title: content?.cta_title ?? fallbackContent.cta_title, cta_description: content?.cta_description ?? fallbackContent.cta_description, cta_primary_label: content?.cta_primary_label ?? fallbackContent.cta_primary_label, cta_primary_url: content?.cta_primary_url ?? fallbackContent.cta_primary_url, cta_secondary_label: content?.cta_secondary_label ?? fallbackContent.cta_secondary_label, cta_secondary_url: content?.cta_secondary_url ?? fallbackContent.cta_secondary_url, cta_image_alt: content?.cta_image_alt ?? '', featured_article_id: content?.featured_article_id ? String(content.featured_article_id) : '', seo_title: seo?.title ?? content?.title ?? fallbackContent.title, seo_description: seo?.description ?? content?.description ?? fallbackContent.description })

export function NewsPageSettingsAdminPage() {
  const client = useQueryClient()
  const query = useQuery({ queryKey: ['admin-news-page'], queryFn: getAdminNewsPage })
  const [form, setForm] = useState<FormState>(toFormState())
  const [errors, setErrors] = useState<Record<string, string[]>>({})
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [uploading, setUploading] = useState(false)

  useEffect(() => { if (query.data) setForm(toFormState(query.data.content, query.data.seo)) }, [query.data])
  const selectedArticle = useMemo(() => query.data?.articles.find((article) => article.id === Number(form.featured_article_id)), [form.featured_article_id, query.data?.articles])
  const setField = <Key extends keyof FormState>(key: Key, value: FormState[Key]) => setForm((current) => ({ ...current, [key]: value }))
  const fieldError = (name: string) => errors[name]?.[0] && <span className="mt-1 block text-sm font-semibold text-red-700">{errors[name][0]}</span>
  const save = useMutation({ mutationFn: () => updateNewsPageContent({ eyebrow: form.eyebrow || null, title: form.title || null, description: form.description || null, featured_article_id: form.featured_article_id ? Number(form.featured_article_id) : null, featured_badge_label: form.featured_badge_label || null, list_eyebrow: form.list_eyebrow || null, list_title: form.list_title || null, list_description: form.list_description || null, show_cta: form.show_cta, cta_eyebrow: form.cta_eyebrow || null, cta_title: form.cta_title || null, cta_description: form.cta_description || null, cta_primary_label: form.cta_primary_label || null, cta_primary_url: form.cta_primary_url || null, cta_secondary_label: form.cta_secondary_label || null, cta_secondary_url: form.cta_secondary_url || null, cta_image_alt: form.cta_image_alt || null, seo: { title: form.seo_title || null, description: form.seo_description || null } }), onError: (error: any) => { setErrors(error.response?.data?.errors ?? {}); toast.error(error.response?.data?.message ?? 'Không thể lưu thiết lập trang bản tin.') } })
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setErrors({}); try { await save.mutateAsync(); if (imageFile) { setUploading(true); await uploadNewsCtaImage(imageFile, form.cta_image_alt); setImageFile(null) }; await Promise.all([client.invalidateQueries({ queryKey: ['admin-news-page'] }), client.invalidateQueries({ queryKey: ['news-page'] })]); toast.success('Đã lưu thiết lập trang bản tin.') } catch { /* handled */ } finally { setUploading(false) } }
  const removeImage = async () => { try { await deleteNewsCtaImage(); await Promise.all([client.invalidateQueries({ queryKey: ['admin-news-page'] }), client.invalidateQueries({ queryKey: ['news-page'] })]); toast.success('Đã xóa ảnh CTA.') } catch { toast.error('Không thể xóa ảnh CTA.') } }

  if (query.isLoading || !query.data) return <LoadingState label="Đang tải thiết lập trang bản tin..." />
  if (query.isError) return <div className="card p-8 text-center"><h1 className="text-xl font-black">Không thể tải thiết lập trang</h1><button className="btn-secondary mt-4" onClick={() => query.refetch()}>Thử lại</button></div>
  return <div className="mx-auto max-w-5xl">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Thiết lập trang bản tin</h1><p className="muted">Quản lý nội dung hiển thị tại /tin-tuc.</p></div><div className="flex flex-wrap gap-2"><Link className="btn-secondary" to="/admin/news">Quay lại bản tin</Link><a className="btn-secondary" href="/tin-tuc" target="_blank" rel="noreferrer">Xem trang <ExternalLink size={16} /></a></div></div>
    <form className="grid gap-6" onSubmit={submit}>
      <section className="card p-5 md:p-6"><h2 className="text-xl font-black">A. Giới thiệu trang</h2><div className="mt-4 grid gap-4"><label><span className="label">Eyebrow</span><input className="input" value={form.eyebrow} onChange={(event) => setField('eyebrow', event.target.value)} maxLength={120} />{fieldError('eyebrow')}</label><label><span className="label">Tiêu đề H1</span><input className="input" value={form.title} onChange={(event) => setField('title', event.target.value)} maxLength={190} />{fieldError('title')}</label><label><span className="label">Mô tả</span><textarea className="input min-h-28" value={form.description} onChange={(event) => setField('description', event.target.value)} maxLength={2000} />{fieldError('description')}</label></div></section>
      <section className="card p-5 md:p-6"><h2 className="text-xl font-black">B. Bài viết nổi bật</h2><div className="mt-4 grid gap-4"><label><span className="label">Chọn bài đã xuất bản</span><select className="input" value={form.featured_article_id} onChange={(event) => setField('featured_article_id', event.target.value)}><option value="">Tự chọn bài mới nhất phù hợp</option>{query.data.articles.map((article) => <option key={article.id} value={article.id}>{article.title}{article.category ? ` · ${article.category}` : ''}</option>)}</select>{fieldError('featured_article_id')}</label>{selectedArticle && <div className="flex flex-wrap items-center gap-4 rounded-2xl border border-[var(--color-border)] bg-[var(--color-background-muted)] p-3">{selectedArticle.cover_image_path ? <img src={resolveAssetUrl(selectedArticle.cover_image_path)} alt="" className="aspect-video w-28 rounded-xl object-cover" /> : <span className="grid aspect-video w-28 place-items-center rounded-xl bg-[var(--color-brand-pale)] text-sm font-black text-[var(--color-brand-deep)]">LS</span>}<div className="min-w-0 flex-1"><strong className="block truncate">{selectedArticle.title}</strong><span className="muted text-sm">{selectedArticle.published_at ? dateFormatter.format(new Date(selectedArticle.published_at)) : 'Đã xuất bản'}</span>{!selectedArticle.has_cover && <span className="mt-1 flex items-center gap-1 text-sm font-semibold text-amber-800"><TriangleAlert size={15} />Nên thêm ảnh bìa cho bài nổi bật.</span>}</div><a className="btn-secondary px-3" href={`/tin-tuc/${selectedArticle.slug}`} target="_blank" rel="noreferrer" aria-label={`Xem ${selectedArticle.title}`}><ExternalLink size={16} /></a></div>}<label><span className="label">Nhãn bài nổi bật</span><input className="input" value={form.featured_badge_label} onChange={(event) => setField('featured_badge_label', event.target.value)} maxLength={120} /></label></div></section>
      <section className="card p-5 md:p-6"><h2 className="text-xl font-black">C. Khu vực bài viết mới</h2><div className="mt-4 grid gap-4"><label><span className="label">Eyebrow</span><input className="input" value={form.list_eyebrow} onChange={(event) => setField('list_eyebrow', event.target.value)} maxLength={120} /></label><label><span className="label">Tiêu đề</span><input className="input" value={form.list_title} onChange={(event) => setField('list_title', event.target.value)} maxLength={190} /></label><label><span className="label">Mô tả</span><textarea className="input min-h-24" value={form.list_description} onChange={(event) => setField('list_description', event.target.value)} maxLength={1000} /></label></div></section>
      <section className="card p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">D. CTA cuối trang</h2><p className="muted mt-1 text-sm">Hiển thị khối tư vấn và điều hướng ở cuối trang.</p></div><label className="inline-flex items-center gap-2 font-bold"><input type="checkbox" checked={form.show_cta} onChange={(event) => setField('show_cta', event.target.checked)} />Hiển thị CTA</label></div><div className="mt-4 grid gap-4"><label><span className="label">Eyebrow</span><input className="input" value={form.cta_eyebrow} onChange={(event) => setField('cta_eyebrow', event.target.value)} maxLength={120} /></label><label><span className="label">Tiêu đề</span><input className="input" value={form.cta_title} onChange={(event) => setField('cta_title', event.target.value)} maxLength={190} /></label><label><span className="label">Mô tả</span><textarea className="input min-h-28" value={form.cta_description} onChange={(event) => setField('cta_description', event.target.value)} maxLength={2000} /></label><div className="grid gap-4 md:grid-cols-2"><label><span className="label">Nút chính</span><input className="input" value={form.cta_primary_label} onChange={(event) => setField('cta_primary_label', event.target.value)} maxLength={120} /></label><label><span className="label">URL nút chính</span><input className="input" value={form.cta_primary_url} onChange={(event) => setField('cta_primary_url', event.target.value)} placeholder="/lien-he hoặc https://..." maxLength={500} />{fieldError('cta_primary_url')}</label><label><span className="label">Nút phụ</span><input className="input" value={form.cta_secondary_label} onChange={(event) => setField('cta_secondary_label', event.target.value)} maxLength={120} /></label><label><span className="label">URL nút phụ</span><input className="input" value={form.cta_secondary_url} onChange={(event) => setField('cta_secondary_url', event.target.value)} placeholder="/san-pham hoặc https://..." maxLength={500} />{fieldError('cta_secondary_url')}</label></div><HomeImageCropEditor title="CTA bản tin" mediaKey="newsCta" description="Ảnh minh họa nằm cạnh nội dung CTA cuối trang." path={query.data.content.cta_image_path} alt={form.cta_image_alt} fallback="/images/product-placeholder.svg" uploading={uploading} onAltChange={(value) => setField('cta_image_alt', value)} onUpload={(file) => setImageFile(file ?? null)} onRemove={() => { void removeImage() }} />{fieldError('cta_image_alt')}{imageFile && <p className="text-sm font-semibold text-slate-600">Ảnh đã cắt sẽ tải lên khi lưu: {imageFile.name}</p>}</div></section>
      <section className="card p-5 md:p-6"><h2 className="text-xl font-black">E. SEO</h2><div className="mt-4 grid gap-4"><label><span className="label">SEO title</span><input className="input" value={form.seo_title} onChange={(event) => setField('seo_title', event.target.value)} maxLength={190} />{fieldError('seo.title')}<span className="muted mt-1 block text-sm">{form.seo_title.length}/190 ký tự</span></label><label><span className="label">SEO description</span><textarea className="input min-h-24" value={form.seo_description} onChange={(event) => setField('seo_description', event.target.value)} maxLength={320} />{fieldError('seo.description')}<span className="muted mt-1 block text-sm">{form.seo_description.length}/320 ký tự</span></label></div></section>
      <div className="sticky bottom-4 z-10 flex justify-end"><button className="btn-primary shadow-lg" type="submit" disabled={save.isPending || uploading}>{save.isPending || uploading ? <Loader2 size={17} className="animate-spin" /> : <Save size={17} />}Lưu thiết lập</button></div>
    </form>
  </div>
}
