import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, MessageSquareReply, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { EmptyState } from '../../components/common/EmptyState'
import { LoadingState } from '../../components/common/LoadingState'
import type { AdminReview, ApiResponse, Pagination } from '../../types'

export function ReviewsAdminPage() {
  const client = useQueryClient(); const [status, setStatus] = useState(''); const [rating, setRating] = useState(''); const [editing, setEditing] = useState<AdminReview | null>(null)
  const query = useQuery({ queryKey: ['admin-reviews', status, rating], queryFn: async () => (await apiClient.get<ApiResponse<Pagination<AdminReview>>>('/admin/reviews', { params: { status: status || undefined, rating: rating || undefined } })).data.data })
  const refresh = () => client.invalidateQueries({ queryKey: ['admin-reviews'] })
  const update = async (review: AdminReview, nextStatus: AdminReview['status'], adminReply = review.admin_reply ?? '') => { await apiClient.patch(`/admin/reviews/${review.id}/status`, { status: nextStatus, admin_reply: adminReply || null }); await refresh(); setEditing(null); toast.success('Đã cập nhật đánh giá.') }
  const reply = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); await update(editing, String(form.get('status')) as AdminReview['status'], String(form.get('admin_reply') ?? '')) }
  const remove = async (review: AdminReview) => { if (!confirm('Xóa vĩnh viễn đánh giá này?')) return; await apiClient.delete(`/admin/reviews/${review.id}`); await refresh(); toast.success('Đã xóa đánh giá.') }
  return <div><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Đánh giá</h1><p className="muted">Kiểm duyệt nội dung và phản hồi khách hàng.</p></div><div className="flex gap-3"><label><span className="label">Trạng thái</span><select className="input min-w-40" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tất cả</option><option value="pending">Chờ duyệt</option><option value="approved">Đã duyệt</option><option value="rejected">Từ chối</option></select></label><label><span className="label">Số sao</span><select className="input min-w-32" value={rating} onChange={(event) => setRating(event.target.value)}><option value="">Tất cả</option>{[5, 4, 3, 2, 1].map((item) => <option key={item} value={item}>{item} sao</option>)}</select></label></div></div>
    {editing && <form className="card mb-6 grid gap-4 p-5" onSubmit={reply}><div className="flex justify-between"><div><h2 className="font-black">Phản hồi đánh giá của {editing.user.name}</h2><p className="muted text-sm">{editing.product.name}</p></div><button type="button" className="btn-secondary px-3" onClick={() => setEditing(null)}><X size={17} /></button></div><textarea className="input min-h-28" name="admin_reply" defaultValue={editing.admin_reply ?? ''} placeholder="Nội dung phản hồi từ cửa hàng" /><div className="flex flex-wrap gap-3"><select className="input max-w-48" name="status" defaultValue={editing.status}><option value="pending">Chờ duyệt</option><option value="approved">Đã duyệt</option><option value="rejected">Từ chối</option></select><button className="btn-primary"><MessageSquareReply size={17} />Lưu phản hồi</button></div></form>}
    {query.isLoading ? <LoadingState /> : query.data?.data.length ? <div className="grid gap-4">{query.data.data.map((review) => <article className="card p-5" key={review.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-black">{review.product.name}</div><div className="muted text-sm">{review.user.name} · {new Date(review.created_at).toLocaleDateString('vi-VN')}</div></div><div className="font-black text-amber-600">{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</div></div><h3 className="mt-4 font-bold">{review.title || 'Không có tiêu đề'}</h3><p className="mt-1 whitespace-pre-wrap text-slate-700">{review.content || 'Không có nội dung.'}</p>{review.admin_reply && <div className="mt-4 rounded-xl bg-emerald-50 p-4"><strong>Phản hồi cửa hàng</strong><p className="mt-1">{review.admin_reply}</p></div>}<div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={() => update(review, 'approved')}><Check size={16} />Duyệt</button><button className="btn-secondary" onClick={() => update(review, 'rejected')}><X size={16} />Từ chối</button><button className="btn-secondary" onClick={() => setEditing(review)}><MessageSquareReply size={16} />Phản hồi</button><button className="btn-secondary text-red-700" onClick={() => remove(review)}><Trash2 size={16} />Xóa</button><span className="self-center rounded-full bg-slate-100 px-3 py-1 text-sm font-bold">{review.status}</span></div></article>)}</div> : <EmptyState title="Không có đánh giá" description="Không có dữ liệu phù hợp với bộ lọc hiện tại." />}</div>
}
