import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Save } from 'lucide-react'
import { type FormEvent } from 'react'
import { toast } from 'sonner'
import { apiClient } from '../../api/apiClient'
import { LoadingState } from '../../components/common/LoadingState'
import type { ApiResponse, StoreSettings } from '../../types'

export function SettingsAdminPage() {
  const client = useQueryClient()
  const query = useQuery({ queryKey: ['admin-settings'], queryFn: async () => (await apiClient.get<ApiResponse<StoreSettings>>('/admin/settings')).data.data })
  if (query.isLoading || !query.data) return <LoadingState />
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { store_name: String(form.get('store_name') ?? ''), support_phone: String(form.get('support_phone') ?? '') || null, support_email: String(form.get('support_email') ?? '') || null, store_address: String(form.get('store_address') ?? '') || null, currency: 'VND', shipping_fee: Number(form.get('shipping_fee')), free_shipping_from: Number(form.get('free_shipping_from')), low_stock_threshold: Number(form.get('low_stock_threshold')), order_prefix: String(form.get('order_prefix') ?? '').toUpperCase() }; try { await apiClient.put('/admin/settings', payload); await client.invalidateQueries({ queryKey: ['admin-settings'] }); toast.success('Đã lưu cấu hình cửa hàng.') } catch { toast.error('Không thể lưu cấu hình. Vui lòng kiểm tra dữ liệu.') } }
  const settings = query.data
  return <div><div className="mb-6"><h1 className="text-3xl font-black">Cài đặt cửa hàng</h1><p className="muted">Cấu hình được lưu trong database và áp dụng cho checkout, vận chuyển, mã đơn.</p></div><form className="card grid gap-5 p-6 md:grid-cols-2" onSubmit={save}><label><span className="label">Tên cửa hàng</span><input className="input" name="store_name" defaultValue={settings.store_name} required /></label><label><span className="label">Tiền tố mã đơn</span><input className="input uppercase" name="order_prefix" defaultValue={settings.order_prefix} required /></label><label><span className="label">Điện thoại hỗ trợ</span><input className="input" name="support_phone" defaultValue={settings.support_phone ?? ''} /></label><label><span className="label">Email hỗ trợ</span><input className="input" type="email" name="support_email" defaultValue={settings.support_email ?? ''} /></label><label className="md:col-span-2"><span className="label">Địa chỉ cửa hàng</span><textarea className="input min-h-24" name="store_address" defaultValue={settings.store_address ?? ''} /></label><label><span className="label">Phí giao hàng (VND)</span><input className="input" type="number" min="0" name="shipping_fee" defaultValue={settings.shipping_fee} required /></label><label><span className="label">Miễn phí từ (VND)</span><input className="input" type="number" min="0" name="free_shipping_from" defaultValue={settings.free_shipping_from} required /></label><label><span className="label">Ngưỡng cảnh báo tồn kho mặc định</span><input className="input" type="number" min="0" name="low_stock_threshold" defaultValue={settings.low_stock_threshold} required /></label><label><span className="label">Tiền tệ</span><input className="input bg-slate-50" value="VND" readOnly /></label><button className="btn-primary justify-self-start md:col-span-2"><Save size={18} />Lưu cấu hình</button></form></div>
}
